const partProgress: string = require("./../../../assets/images/modal/part-progress.png");
const newbieBg: string = require("./../../../assets/images/daily/newbie-bg.png");
const newbieDay0: string = require("./../../../assets/images/daily/newbie-day-0.png");
const newbieDay1: string = require("./../../../assets/images/daily/newbie-day-1.png");
const newbieDay2: string = require("./../../../assets/images/daily/newbie-day-2.png");
const newbieDay3: string = require("./../../../assets/images/daily/newbie-day-3.png");
const newbieDay4: string = require("./../../../assets/images/daily/newbie-day-4.png");
const newbieDay5: string = require("./../../../assets/images/daily/newbie-day-5.png");
const newbieDay6: string = require("./../../../assets/images/daily/newbie-day-6.png");
const newbieDay7: string = require("./../../../assets/images/daily/newbie-day-7.png");
const dayYellow: string = require("./../../../assets/images/daily/day-yellow.png");
const dayPurple: string = require("./../../../assets/images/daily/day-purple.png");
const dayRed: string = require("./../../../assets/images/daily/day-red.png");
const awardReceived: string = require("./../../../assets/images/daily/award-received.png");
const donateBg: string = require("./../../../assets/images/modal/donate.png");
const doneChapterButton: string = require("./../../../assets/images/modal/done-chapter-button.png");
const dailyBg: string = require("./../../../assets/images/modal/daily-bg.png");
const middleButton: string = require("./../../../assets/images/modal/middle-button.png");
const sysSwitch: string = require("./../../../assets/images/modal/sys-switch.png");
const awardBg: string = require("./../../../assets/images/icons/award-bg.png");
const achievementDaily: string = require("./../../../assets/images/modal/achievement-daily.png");
const flashDaily: string = require("./../../../assets/images/modal/flash-daily.png");
const award3: string = require("./../../../assets/images/icons/award-3.png");
const award4: string = require("./../../../assets/images/icons/award-4.png");
const award5: string = require("./../../../assets/images/icons/award-5.png");
const doneChapter: string = require("./../../../assets/images/modal/done-chapter.png");
const pbChapterAnimal: string = require("./../../../assets/images/modal/pb-chapter-modal.png");
const greenProgress: string = require("./../../../assets/images/modal/green-progress.png");
const farmer: string = require("./../../../assets/images/farmer.png");
const tasksTop: string = require("./../../../assets/images/modal/tasks-top.png");
const tasksMiddle: string = require("./../../../assets/images/modal/tasks-middle.png");
const tasksBottom: string = require("./../../../assets/images/modal/tasks-bottom.png");
const tasksComplete: string = require("./../../../assets/images/modal/tasks-complete.png");
const tasksUncomplete: string = require("./../../../assets/images/modal/tasks-uncomplete.png");
const tasksReward: string = require("./../../../assets/images/modal/tasks-reward.png");
const tasksBar: string = require("./../../../assets/images/modal/tasks-bar.png");
const tasksClose: string = require("./../../../assets/images/modal/tasks-close.png");
const socialTaskBg: string = require("./../../../assets/images/modal/social-task-bg.png");
const socialTaskTop: string = require("./../../../assets/images/modal/social-task-top.png");
const socialTaskBottom: string = require("./../../../assets/images/modal/social-task-bottom.png");
const socialTaskMiddle: string = require("./../../../assets/images/modal/social-task-middle.png");
const bigButtonGrey: string = require("./../../../assets/images/modal/btn_l_lock.png");
const bigButtonBlue: string = require("./../../../assets/images/modal/btn_lb.png");
const bigButtonOrange: string = require("./../../../assets/images/modal/btn_lo.png");
const bigButtonRed: string = require("./../../../assets/images/modal/btn_lr.png");
const bigButtonYellow: string = require("./../../../assets/images/modal/btn_ly.png");
const repositorySellBtn: string = require("./../../../assets/images/modal/repository-sell-btn.png");
const herdBoostRoadSheep: string = require("./../../../assets/images/sheep/herd-boost-road-sheep.png");
const herdBoostRoadChicken: string = require("./../../../assets/images/chicken/herd-boost-road-chicken.png");
const herdBoostRoadCow: string = require("./../../../assets/images/cow/herd-boost-road-cow.png");
const herdBoostRoadEvent: string = require("./../../../assets/images/event/herd-boost-road-event.png");
const badMergingAnimation: string = require("./../../../assets/images/bad-merging-animation.png");
const boostWindowBg: string = require("./../../../assets/images/boost/background.png");
const boostCountdown: string = require("./../../../assets/images/boost/countdown.png");
const boostLeaves: string = require("./../../../assets/images/boost/leaves.png");
const flags: string = require("./../../../assets/images/modal/flags.png");
const chatBackground: string = require("./../../../assets/images/modal/chat/bg.png");
const chatDeleteBg: string = require("./../../../assets/images/modal/chat/delete-bg.png");
const chatTrash: string = require("./../../../assets/images/modal/chat/trash.png");
const chatArrow: string = require("./../../../assets/images/modal/chat/arrow.png");
const chatTab: string = require('./../../../assets/images/modal/chat/tab.png');
const chatTabClose: string = require('./../../../assets/images/modal/chat/tab-close.png');
const chatForeignMessageBg: string = require('./../../../assets/images/modal/chat/foreign-message-bg.png');
const chatClanMessageBg: string = require('./../../../assets/images/modal/chat/clan-message-bg.png');
const chatAdminMessageBg: string = require('./../../../assets/images/modal/chat/admin-message-bg.png');
const chatUserMessageBg: string = require('./../../../assets/images/modal/chat/user-message-bg.png');
const chatTabActive: string = require('./../../../assets/images/modal/chat/tab-active.png');
const chatInput: string = require('./../../../assets/images/modal/chat/input.png');
const chatSendBtn: string = require("./../../../assets/images/modal/chat/send-btn.png");
const chatEmojiBtn: string = require("./../../../assets/images/modal/chat/emoji-btn.png");
const autoprogressBG: string = require("./../../../assets/images/event/modal/autoprogress-bg.png");
const purpleBtn: string = require("./../../../assets/images/event/modal/purple-btn.png");
const ratingBG: string = require("./../../../assets/images/event/modal/rating-bg.png");
const shopBtn: string = require("./../../../assets/images/modal/shop-btn.png");
const shopBtnDisable: string = require("./../../../assets/images/modal/shop-btn-disable.png");
const ratingRulesBtn: string = require("./../../../assets/images/event/modal/rating-rules-btn.png");
const ratingPriseBtn: string = require("./../../../assets/images/event/modal/rating-price-btn.png");
const ratingPrisePlaces: string = require("./../../../assets/images/event/modal/rating-places.png");
const ratingBGAfter: string = require("./../../../assets/images/event/modal/raiting-bg-after.png");
const unicornStatus: string = require("./../../../assets/images/icons/unicorn-status.png");
const feedBoostChickenIcon: string = require("./../../../assets/images/icons/chicken-feed-boost.png");
const feedBoostCowIcon: string = require("./../../../assets/images/icons/cow-feed-boost.png");
const factoryWindow: string = require('./../../../assets/images/cow/modal/factory-window.png');
const factoryWheel: string = require('./../../../assets/images/cow/modal/factory-wheel.png');
const factoryProduction1: string = require('./../../../assets/images/cow/modal/factory-resource-1.png');
const factoryProduction2: string = require('./../../../assets/images/cow/modal/factory-resource-2.png');
const factoryProduction3: string = require('./../../../assets/images/cow/modal/factory-resource-3.png');
const factoryProduction4: string = require('./../../../assets/images/cow/modal/factory-resource-4.png');
const factoryCacao: string = require('./../../../assets/images/cow/modal/factory-cacao.png');
const factoryProductionSlot2: string = require('./../../../assets/images/cow/modal/factory-resource-slot-2.png');
const factoryProductionSlotDisable2: string = require('./../../../assets/images/cow/modal/factory-resource-slot-disable-2.png');
const factoryProductionSlot3: string = require('./../../../assets/images/cow/modal/factory-resource-slot-3.png');
const factoryProductionSlotDisable3: string = require('./../../../assets/images/cow/modal/factory-resource-slot-disable-3.png');
const factoryProductionSlot4: string = require('./../../../assets/images/cow/modal/factory-resource-slot-4.png');
const factoryProductionSlotDisable4: string = require('./../../../assets/images/cow/modal/factory-resource-slot-disable-4.png');
const profileWindowBtnYellow: string = require('./../../../assets/images/modal/profile-window-button-yellow.png');
const profileWindowBtnRed: string = require('./../../../assets/images/modal/profile-window-button-red.png');
const profileWindowBtnGreen: string = require('./../../../assets/images/modal/profile-window-button-green.png');
const profileWindowSettingsBtn: string = require('./../../../assets/images/modal/profile-window-settings-btn.png');
const profileWindowFooter: string = require('./../../../assets/images/modal/profile-window-footer.png');
const profileWindowHeader: string = require('./../../../assets/images/modal/profile-window-header.png');
const profileWindowLevel: string = require('./../../../assets/images/modal/profile-window-level.png');
const profileWindowBg: string = require('./../../../assets/images/modal/profile-window-plate.png');
const settingsWindowHeader: string = require('./../../../assets/images/modal/settings/header.png');
const settingsWindowMinus: string = require('./../../../assets/images/modal/settings/minus.png');
const settingsWindowPlus: string = require('./../../../assets/images/modal/settings/plus.png');
const settingsWindowSegment: string = require('./../../../assets/images/modal/settings/segment.png');
const settingsWindowMusicPlate: string = require('./../../../assets/images/modal/settings/music-plate.png');
const settingsWindowSoundPlate: string = require('./../../../assets/images/modal/settings/sound-plate.png');
const squareBg: string = require('../../../assets/images/modal/square-bg.png');
const clanWindowHeader: string = require('../../../assets/images/modal/clan/header.png');
const clanWindowTabActive: string = require('../../../assets/images/modal/clan/tab-active.png');
const clanWindowTabDisable: string = require('../../../assets/images/modal/clan/tab-disable.png');
const clanWindowTabClose: string = require('../../../assets/images/modal/clan/tab-close.png');
const clanWindowCrown: string = require('../../../assets/images/modal/clan/сrown.png');
const clanWindowLine: string = require('../../../assets/images/modal/clan/line.png');
const clanWindowMedalBronze: string = require('../../../assets/images/modal/clan/medal-bronze.png');
const clanWindowMedalGold: string = require('../../../assets/images/modal/clan/medal-gold.png');
const clanWindowMedalSilver: string = require('../../../assets/images/modal/clan/medal-silver.png');
const clanWindowMedal: string = require('../../../assets/images/modal/clan/medal.png');
const clanWindowLeaderPlate: string = require('../../../assets/images/modal/clan/leader-plate.png');
const clanWindowSearchPlate: string = require('../../../assets/images/modal/clan/search-plate.png');
const clanWindowPointsBg: string = require('../../../assets/images/modal/clan/points-bg.png');
const clanWindowWreath: string = require('../../../assets/images/modal/clan/wreath.png');

export default function typePreload(): void {
    switch (this.state.modal.type) {
      case 1: // системное окно
        this.load.image('unicorn-status', unicornStatus);
        this.load.image('farmer', farmer);
        this.load.image('pb-chapter-modal', pbChapterAnimal);
        this.load.image('big-btn-grey', bigButtonGrey);
        this.load.image('big-btn-blue', bigButtonBlue);
        this.load.image('big-btn-orange', bigButtonOrange);
        this.load.image('big-btn-red', bigButtonRed);
        this.load.image('big-btn-yellow', bigButtonYellow);
        this.load.image('repository-sell-btn', repositorySellBtn);
        this.load.image('green-progress', greenProgress);
        this.load.image('middle-button', middleButton);    
        this.load.image('sys-switch', sysSwitch);
        break;
      case 2: // магазин
        // this.load.image('shop-window', shopWindow);
        if (this.state.farm === 'Chicken') this.load.image('chicken-feed-boost-icon', feedBoostChickenIcon); 
        else if (this.state.farm === 'Cow') this.load.image('cow-feed-boost-icon', feedBoostCowIcon); 
        
        break;
      case 3: // окно с заданиями
        this.load.image('tasks-top', tasksTop);
        this.load.image('tasks-middle', tasksMiddle);
        this.load.image('tasks-bottom', tasksBottom);
        this.load.image('tasks-complete', tasksComplete);
        this.load.image('tasks-uncomplete', tasksUncomplete);
        this.load.image('tasks-reward', tasksReward);
        this.load.image('tasks-bar', tasksBar);
        this.load.image('tasks-close', tasksClose);
        this.load.image('part-progress', partProgress);

        break;
      case 4: // ежедневные награды +
        this.load.image('award-bg', awardBg);
        this.load.image('daily-bg', dailyBg);
        this.load.image('achievement-daily', achievementDaily);
        this.load.image('flash-daily', flashDaily);
        this.load.image('middle-button', middleButton);
        this.load.image('award-3', award3);
        this.load.image('award-4', award4);
        this.load.image('award-5', award5);
        break;
      case 5: // следующая глава +
        this.load.image('done-chapter', doneChapter);
        this.load.image('done-chapter-button', doneChapterButton);

        break;
      case 6: // ежедневные награды новичков +
        this.load.image('newbie-bg', newbieBg);
        this.load.image('newbie-day-0', newbieDay0);
        this.load.image('newbie-day-1', newbieDay1);
        this.load.image('newbie-day-2', newbieDay2);
        this.load.image('newbie-day-3', newbieDay3);
        this.load.image('newbie-day-4', newbieDay4);
        this.load.image('newbie-day-5', newbieDay5);
        this.load.image('newbie-day-6', newbieDay6);
        this.load.image('newbie-day-7', newbieDay7);
        this.load.image('day-yellow', dayYellow);
        this.load.image('day-purple', dayPurple);
        this.load.image('day-red', dayRed);
        this.load.image('award-received', awardReceived);
        this.load.image('tasks-close', tasksClose);
        break;
      case 7: // окно выдачи донатных кристаллов +
        this.load.image('done-chapter-button', doneChapterButton);
        this.load.image('donate', donateBg);
        break;
      case 8: // окно стадного буста +
        if (this.state.farm === 'Sheep') this.load.image('herd-boost-road-sheep', herdBoostRoadSheep);
        if (this.state.farm === 'Chicken') this.load.image('herd-boost-road-chicken', herdBoostRoadChicken);
        if (this.state.farm === 'Cow') this.load.image('herd-boost-road-cow', herdBoostRoadCow);
        if (this.state.farm === 'Unicorn') this.load.image('herd-boost-road-unicorn', herdBoostRoadEvent);
        this.load.image('bad-merging-animation', badMergingAnimation);
        this.load.image('boost-window-bg', boostWindowBg);
        this.load.image('boost-countdown', boostCountdown);
        this.load.image('boost-leaves', boostLeaves);
        this.load.image('flags', flags);
        break;
      case 9: // Чат +
        this.load.image('chat-bg', chatBackground);
        this.load.image('chat-delete-bg', chatDeleteBg);
        this.load.image('chat-trash', chatTrash);
        this.load.image('chat-arrow', chatArrow);
        this.load.image('chat-tab', chatTab);
        this.load.image('chat-foreign-message-bg', chatForeignMessageBg);
        this.load.image('chat-clan-message-bg', chatClanMessageBg);
        this.load.image('chat-admin-message-bg', chatAdminMessageBg);
        this.load.image('chat-user-message-bg', chatUserMessageBg);
        this.load.image('chat-tab-close', chatTabClose);
        this.load.image('chat-tab-active', chatTabActive);
        this.load.image('chat-input-bg', chatInput);
        this.load.image('chat-send-btn', chatSendBtn);
        this.load.image('chat-emoji-btn', chatEmojiBtn);
        this.load.image('unicorn-status', unicornStatus);
        this.load.image('profile-window-button-yellow', profileWindowBtnYellow);
        this.load.image('profile-window-button-red', profileWindowBtnRed);
        this.load.image('profile-window-button-green', profileWindowBtnGreen);
        break;
      case 10: // окно автопрогресса ивентовой фермы +
        this.load.image('autoprogress-bg', autoprogressBG);
        this.load.image('purple-btn', purpleBtn);
        break;
      case 11: // окно рейтингов ивентовой фермы +
        this.load.image('rating-bg', ratingBG);
        this.load.image('rating-rules-btn', ratingRulesBtn);
        this.load.image('rating-price-btn', ratingPriseBtn);
        this.load.image('rating-places', ratingPrisePlaces);
        this.load.image('unicorn-status', unicornStatus);
        this.load.image('tasks-close', tasksClose);
        break;
      case 12: // окно выдачи наград ивентовой фермы +
        this.load.image('raiting-bg-after',ratingBGAfter);
        this.load.image('rating-places', ratingPrisePlaces);
        this.load.image('rating-rules-btn', ratingRulesBtn);
        this.load.image('rating-price-btn', ratingPriseBtn);
        this.load.image('unicorn-status', unicornStatus);
        this.load.image('tasks-close', tasksClose);

        break;
      case 13:
        this.load.image('factory-window', factoryWindow);
        this.load.image('factory-wheel', factoryWheel);
        this.load.image('factory-production-1', factoryProduction1);
        this.load.image('factory-production-2', factoryProduction2);
        this.load.image('factory-production-3', factoryProduction3);
        this.load.image('factory-production-4', factoryProduction4);
        this.load.image('factory-cacao', factoryCacao);
        this.load.image('factory-production-slot-2', factoryProductionSlot2);
        this.load.image('factory-production-slot-disable-2', factoryProductionSlotDisable2);
        this.load.image('factory-production-slot-3', factoryProductionSlot3);
        this.load.image('factory-production-slot-disable-3', factoryProductionSlotDisable3);
        this.load.image('factory-production-slot-4', factoryProductionSlot4);
        this.load.image('factory-production-slot-disable-4', factoryProductionSlotDisable4);
        this.load.image('tasks-close', tasksClose);
        break;
      case 14: 
        this.load.image('social-task-bg', socialTaskBg);
        this.load.image('social-task-top', socialTaskTop);
        this.load.image('social-task-bottom', socialTaskBottom);
        this.load.image('social-task-middle', socialTaskMiddle);
        this.load.image('shop-btn', shopBtn);
        this.load.image('shop-btn-disable', shopBtnDisable);
        this.load.image('tasks-close', tasksClose);
        break;
      case 15: 
        this.load.image('profile-window-settings-btn', profileWindowSettingsBtn);
        this.load.image('profile-window-footer', profileWindowFooter);
        this.load.image('profile-window-header', profileWindowHeader);
        this.load.image('profile-window-level', profileWindowLevel);
        this.load.image('profile-window-bg', profileWindowBg);
        this.load.image('profile-window-button-yellow', profileWindowBtnYellow);
        this.load.image('profile-window-button-red', profileWindowBtnRed);
        this.load.image('profile-window-button-green', profileWindowBtnGreen);
        this.load.image('tasks-close', tasksClose);
        break;
      case 16: 
      this.load.image('settings-window-header', settingsWindowHeader);
      this.load.image('settings-window-minus', settingsWindowMinus);
      this.load.image('settings-window-plus', settingsWindowPlus);
      this.load.image('settings-window-segment', settingsWindowSegment);
      this.load.image('settings-window-music-plate', settingsWindowMusicPlate);
      this.load.image('settings-window-sound-plate', settingsWindowSoundPlate);
      this.load.image('tasks-close', tasksClose);
        break;
      case 17: 
      this.load.image('modal-square-bg', squareBg);
      this.load.image('clan-window-header', clanWindowHeader);
      this.load.image('clan-window-tab-active', clanWindowTabActive);
      this.load.image('clan-window-tab-disable', clanWindowTabDisable);
      this.load.image('clan-window-tab-close', clanWindowTabClose);
      this.load.image('clan-window-crown', clanWindowCrown);
      this.load.image('clan-window-line', clanWindowLine);
      this.load.image('tasks-close', tasksClose);
      this.load.image('clan-window-medal-bronze', clanWindowMedalBronze);
      this.load.image('clan-window-medal-gold', clanWindowMedalGold);
      this.load.image('clan-window-medal-silver', clanWindowMedalSilver);
      this.load.image('clan-window-medal', clanWindowMedal);
      this.load.image('clan-window-leader-plate', clanWindowLeaderPlate);
      this.load.image('clan-window-search-plate', clanWindowSearchPlate);
      this.load.image('clan-window-points-bg', clanWindowPointsBg);
      this.load.image('clan-window-wreath', clanWindowWreath);
        break;
      default:
        break;
    }
    
}