import { tabActiveAtlas, tabAtlas } from '../../data/atlases';
import Utils from './../../libs/Utils';
import assets from '../../data/assets';


export default function typePreload(): void {
    switch (this.state.modal.type) {
      case 1: // системное окно
        this.load.image('unicorn-status', assets.unicornStatus);
        this.load.image('farmer', assets.farmer);
        this.load.image('pb-chapter-modal', assets.pbChapterAnimal);
        this.load.image('big-btn-grey', assets.bigButtonGrey);
        this.load.image('big-btn-blue', assets.bigButtonBlue);
        this.load.image('big-btn-orange', assets.bigButtonOrange);
        this.load.image('big-btn-red', assets.bigButtonRed);
        this.load.image('big-btn-yellow', assets.bigButtonYellow);
        this.load.image('repository-sell-btn', assets.repositorySellBtn);
        this.load.image('green-progress', assets.greenProgress);
        this.load.image('middle-button', assets.middleButton);    
        this.load.image('sys-switch', assets.sysSwitch);
        break;
      case 2: // магазин
        // this.load.image('shop-window', shopWindow);
        if (this.state.farm === 'Chicken') this.load.image('chicken-feed-boost-icon', assets.feedBoostChickenIcon); 
        else if (this.state.farm === 'Cow') this.load.image('cow-feed-boost-icon', assets.feedBoostCowIcon); 
        
        break;
      case 3: // окно с заданиями
        this.load.image('tasks-top', assets.tasksTop);
        this.load.image('tasks-middle', assets.tasksMiddle);
        this.load.image('tasks-bottom', assets.tasksBottom);
        this.load.image('tasks-uncomplete', assets.tasksUncomplete);
        this.load.image('tasks-reward', assets.tasksReward);
        this.load.image('tasks-bar', assets.tasksBar);
        this.load.image('close-window-btn', assets.closeWindowBtn);
        this.load.image('part-progress', assets.partProgress);
        break;
      case 4: // ежедневные награды +
        this.load.image('award-bg', assets.awardBg);
        this.load.image('daily-bg', assets.dailyBg);
        this.load.image('achievement-daily', assets.achievementDaily);
        this.load.image('flash-daily', assets.flashDaily);
        this.load.image('middle-button', assets.middleButton);
        this.load.image('award-3', assets.award3);
        this.load.image('award-4', assets.award4);
        this.load.image('award-5', assets.award5);
        break;
      case 5: // следующая глава +
        this.load.image('done-chapter', assets.doneChapter);
        this.load.image('done-chapter-button', assets.doneChapterButton);
        if (this.state.farm === 'Cow') {
          if ( Utils.checkTestB(this.state)) {
            this.load.image('cow-chapter-1', assets.cowChapter1testB);
            this.load.image('cow-chapter-2', assets.cowChapter2testB);
            this.load.image('cow-chapter-3', assets.cowChapter3testB);
            this.load.image('cow-chapter-4', assets.cowChapter4testB);
            this.load.image('cow-chapter-5', assets.cowChapter5testB);
            this.load.image('cow-chapter-6', assets.cowChapter1testB);
            this.load.image('cow-chapter-7', assets.cowChapter6testB);
            this.load.image('cow-chapter-8', assets.cowChapter1testB);
            this.load.image('cow-chapter-9', assets.cowChapter3testB);
            this.load.image('cow-chapter-10', assets.cowChapter1testB);
            this.load.image('cow-chapter-11', assets.cowChapter3testB);
            this.load.image('cow-chapter-12', assets.cowChapter1testB);
            this.load.image('cow-chapter-13', assets.cowChapter3testB);
            this.load.image('cow-chapter-14', assets.cowChapter1testB);
            this.load.image('cow-chapter-15', assets.cowChapter3testB);
            this.load.image('cow-chapter-16', assets.cowChapter1testB);
            this.load.image('cow-chapter-17', assets.cowChapter3testB);
            this.load.image('cow-chapter-18', assets.cowChapter1testB);
            this.load.image('cow-chapter-19', assets.cowChapter3testB);
          } else {
            this.load.image('cow-chapter-1', assets.cowChapter1);
            this.load.image('cow-chapter-2', assets.cowChapter2);
            this.load.image('cow-chapter-3', assets.cowChapter3);
            this.load.image('cow-chapter-4', assets.cowChapter4);
            this.load.image('cow-chapter-5', assets.cowChapter5);
            this.load.image('cow-chapter-6', assets.cowChapter6);
            this.load.image('cow-chapter-7', assets.cowChapter7);
            this.load.image('cow-chapter-8', assets.cowChapter8);
            this.load.image('cow-chapter-9', assets.cowChapter9);
            this.load.image('cow-chapter-10', assets.cowChapter10);
            this.load.image('cow-chapter-11', assets.cowChapter11);
            this.load.image('cow-chapter-12', assets.cowChapter12);
            this.load.image('cow-chapter-13', assets.cowChapter13);
            this.load.image('cow-chapter-14', assets.cowChapter14);
            this.load.image('cow-chapter-15', assets.cowChapter15);
            this.load.image('cow-chapter-16', assets.cowChapter16);
          }
        } else if (this.state.farm === 'Sheep') {
          if ( Utils.checkTestB(this.state)) {
            this.load.image('sheep-chapter-1', assets.sheepChapter1testB);
            this.load.image('sheep-chapter-2', assets.sheepChapter2testB);
            this.load.image('sheep-chapter-3', assets.sheepChapter3testB);
            this.load.image('sheep-chapter-4', assets.sheepChapter4testB);
            this.load.image('sheep-chapter-5', assets.sheepChapter5testB);
            this.load.image('sheep-chapter-6', assets.sheepChapter1testB);
            this.load.image('sheep-chapter-7', assets.sheepChapter6testB);
            this.load.image('sheep-chapter-8', assets.sheepChapter1testB);
            this.load.image('sheep-chapter-9', assets.sheepChapter3testB);
            this.load.image('sheep-chapter-10', assets.sheepChapter1testB);
            this.load.image('sheep-chapter-11', assets.sheepChapter3testB);
            this.load.image('sheep-chapter-12', assets.sheepChapter1testB);
            this.load.image('sheep-chapter-13', assets.sheepChapter3testB);
            this.load.image('sheep-chapter-14', assets.sheepChapter1testB);
            this.load.image('sheep-chapter-15', assets.sheepChapter3testB);
            this.load.image('sheep-chapter-16', assets.sheepChapter1testB);
            this.load.image('sheep-chapter-17', assets.sheepChapter3testB);
            this.load.image('sheep-chapter-18', assets.sheepChapter1testB);
            this.load.image('sheep-chapter-19', assets.sheepChapter3testB);
          } else {
            this.load.image('sheep-chapter-1', assets.sheepChapter1);
            this.load.image('sheep-chapter-2', assets.sheepChapter2);
            this.load.image('sheep-chapter-3', assets.sheepChapter3);
            this.load.image('sheep-chapter-4', assets.sheepChapter4);
            this.load.image('sheep-chapter-5', assets.sheepChapter5);
            this.load.image('sheep-chapter-6', assets.sheepChapter6);
            this.load.image('sheep-chapter-7', assets.sheepChapter7);
            this.load.image('sheep-chapter-8', assets.sheepChapter8);
            this.load.image('sheep-chapter-9', assets.sheepChapter9);
            this.load.image('sheep-chapter-10', assets.sheepChapter10);
            this.load.image('sheep-chapter-11', assets.sheepChapter11);
            this.load.image('sheep-chapter-12', assets.sheepChapter12);
            this.load.image('sheep-chapter-13', assets.sheepChapter13);
            this.load.image('sheep-chapter-14', assets.sheepChapter14);
            this.load.image('sheep-chapter-15', assets.sheepChapter15);
            this.load.image('sheep-chapter-16', assets.sheepChapter16);
          }
        } else if (this.state.farm === 'Chicken') {
          if ( Utils.checkTestB(this.state)) {
            this.load.image('chicken-chapter-1', assets.chickenChapter1testB);
            this.load.image('chicken-chapter-2', assets.chickenChapter2testB);
            this.load.image('chicken-chapter-3', assets.chickenChapter3testB);
            this.load.image('chicken-chapter-4', assets.chickenChapter4testB);
            this.load.image('chicken-chapter-5', assets.chickenChapter5testB);
            this.load.image('chicken-chapter-6', assets.chickenChapter1testB);
            this.load.image('chicken-chapter-7', assets.chickenChapter6testB);
            this.load.image('chicken-chapter-8', assets.chickenChapter1testB);
            this.load.image('chicken-chapter-9', assets.chickenChapter3testB);
            this.load.image('chicken-chapter-10', assets.chickenChapter1testB);
            this.load.image('chicken-chapter-11', assets.chickenChapter3testB);
            this.load.image('chicken-chapter-12', assets.chickenChapter1testB);
            this.load.image('chicken-chapter-13', assets.chickenChapter3testB);
            this.load.image('chicken-chapter-14', assets.chickenChapter1testB);
            this.load.image('chicken-chapter-15', assets.chickenChapter3testB);
            this.load.image('chicken-chapter-16', assets.chickenChapter1testB);
            this.load.image('chicken-chapter-17', assets.chickenChapter3testB);
            this.load.image('chicken-chapter-18', assets.chickenChapter1testB);
            this.load.image('chicken-chapter-19', assets.chickenChapter3testB);
          } else {
            this.load.image('chicken-chapter-1', assets.chickenChapter1);
            this.load.image('chicken-chapter-2', assets.chickenChapter2);
            this.load.image('chicken-chapter-3', assets.chickenChapter3);
            this.load.image('chicken-chapter-4', assets.chickenChapter4);
            this.load.image('chicken-chapter-5', assets.chickenChapter5);
            this.load.image('chicken-chapter-6', assets.chickenChapter6);
            this.load.image('chicken-chapter-7', assets.chickenChapter7);
            this.load.image('chicken-chapter-8', assets.chickenChapter8);
            this.load.image('chicken-chapter-9', assets.chickenChapter9);
            this.load.image('chicken-chapter-10', assets.chickenChapter10);
            this.load.image('chicken-chapter-11', assets.chickenChapter11);
            this.load.image('chicken-chapter-12', assets.chickenChapter12);
            this.load.image('chicken-chapter-13', assets.chickenChapter13);
            this.load.image('chicken-chapter-14', assets.chickenChapter14);
            this.load.image('chicken-chapter-15', assets.chickenChapter15);
            this.load.image('chicken-chapter-16', assets.chickenChapter16);
          }
        }
        break;
      case 6: // ежедневные награды новичков +
        this.load.image('newbie-bg', assets.newbieBg);
        this.load.image('newbie-day-0', assets.newbieDay0);
        this.load.image('newbie-day-1', assets.newbieDay1);
        this.load.image('newbie-day-2', assets.newbieDay2);
        this.load.image('newbie-day-3', assets.newbieDay3);
        this.load.image('newbie-day-4', assets.newbieDay4);
        this.load.image('newbie-day-5', assets.newbieDay5);
        this.load.image('newbie-day-6', assets.newbieDay6);
        this.load.image('newbie-day-7', assets.newbieDay7);
        this.load.image('day-yellow', assets.dayYellow);
        this.load.image('day-purple', assets.dayPurple);
        this.load.image('day-red', assets.dayRed);
        this.load.image('award-received', assets.awardReceived);
        this.load.image('close-window-btn', assets.closeWindowBtn);
        break;
      case 7: // окно выдачи донатных кристаллов +
        this.load.image('done-chapter-button', assets.doneChapterButton);
        this.load.image('donate', assets.donateBg);
        break;
      case 8: // окно стадного буста +
        if (this.state.farm === 'Sheep') this.load.image('herd-boost-road-sheep', assets.herdBoostRoadSheep);
        if (this.state.farm === 'Chicken') this.load.image('herd-boost-road-chicken', assets.herdBoostRoadChicken);
        if (this.state.farm === 'Cow') this.load.image('herd-boost-road-cow', assets.herdBoostRoadCow);
        if (this.state.farm === 'Unicorn') this.load.image('herd-boost-road-unicorn', assets.herdBoostRoadEvent);
        this.load.image('bad-merging-animation', assets.badMergingAnimation);
        this.load.image('boost-window-bg', assets.boostWindowBg);
        this.load.image('boost-countdown', assets.boostCountdown);
        this.load.image('boost-leaves', assets.boostLeaves);
        this.load.image('flags', assets.flags);
        break;
      case 9: // Чат +
        this.load.image('chat-bg', assets.chatBackground);
        this.load.image('chat-delete-bg', assets.chatDeleteBg);
        this.load.image('chat-trash', assets.chatTrash);
        this.load.image('chat-arrow', assets.chatArrow);
        this.load.atlas('chat-tab', assets.chatTab, tabAtlas);
        this.load.image('chat-foreign-message-bg', assets.chatForeignMessageBg);
        this.load.image('chat-clan-message-bg', assets.chatClanMessageBg);
        this.load.image('chat-admin-message-bg', assets.chatAdminMessageBg);
        this.load.image('chat-user-message-bg', assets.chatUserMessageBg);
        this.load.image('chat-tab-close', assets.chatTabClose);
        this.load.atlas('chat-tab-active', assets.chatTabActive, tabActiveAtlas);
        this.load.image('chat-input-bg', assets.chatInput);
        this.load.image('chat-send-btn', assets.chatSendBtn);
        this.load.image('chat-emoji-btn', assets.chatEmojiBtn);
        this.load.image('unicorn-status', assets.unicornStatus);
        this.load.image('profile-window-button-yellow', assets.profileWindowBtnYellow);
        this.load.image('profile-window-button-red', assets.profileWindowBtnRed);
        this.load.image('profile-window-button-green', assets.profileWindowBtnGreen);
        break;
      case 10: // окно автопрогресса ивентовой фермы +
        this.load.image('autoprogress-bg', assets.autoprogressBG);
        this.load.image('purple-btn', assets.purpleBtn);
        break;
      case 11: // окно рейтингов ивентовой фермы +
        this.load.image('rating-bg', assets.ratingBG);
        this.load.image('rating-rules-btn', assets.ratingRulesBtn);
        this.load.image('rating-price-btn', assets.ratingPriseBtn);
        this.load.image('rating-places', assets.ratingPrisePlaces);
        this.load.image('unicorn-status', assets.unicornStatus);
        this.load.image('close-window-btn', assets.closeWindowBtn);
        break;
      case 12: // окно выдачи наград ивентовой фермы +
        this.load.image('raiting-bg-after', assets.ratingBGAfter);
        this.load.image('rating-places', assets.ratingPrisePlaces);
        this.load.image('rating-rules-btn', assets.ratingRulesBtn);
        this.load.image('rating-price-btn', assets.ratingPriseBtn);
        this.load.image('unicorn-status', assets.unicornStatus);
        this.load.image('close-window-btn', assets.closeWindowBtn);

        break;
      case 13:
        this.load.image('factory-window', assets.factoryWindow);
        this.load.image('factory-wheel', assets.factoryWheel);
        this.load.image('factory-production-1', assets.factoryProduction1);
        this.load.image('factory-production-2', assets.factoryProduction2);
        this.load.image('factory-production-3', assets.factoryProduction3);
        this.load.image('factory-production-4', assets.factoryProduction4);
        this.load.image('factory-cacao', assets.factoryCacao);
        this.load.image('factory-production-slot-2', assets.factoryProductionSlot2);
        this.load.image('factory-production-slot-disable-2', assets.factoryProductionSlotDisable2);
        this.load.image('factory-production-slot-3', assets.factoryProductionSlot3);
        this.load.image('factory-production-slot-disable-3', assets.factoryProductionSlotDisable3);
        this.load.image('factory-production-slot-4', assets.factoryProductionSlot4);
        this.load.image('factory-production-slot-disable-4', assets.factoryProductionSlotDisable4);
        this.load.image('close-window-btn', assets.closeWindowBtn);
        break;
      case 14: 
        this.load.image('social-task-bg', assets.socialTaskBg);
        this.load.image('social-task-top', assets.socialTaskTop);
        this.load.image('social-task-bottom', assets.socialTaskBottom);
        this.load.image('social-task-middle', assets.socialTaskMiddle);
        this.load.image('shop-btn', assets.shopBtn);
        this.load.image('shop-btn-disable', assets.shopBtnDisable);
        this.load.image('close-window-btn', assets.closeWindowBtn);
        break;
      case 15: 
        this.load.image('profile-window-settings-btn', assets.profileWindowSettingsBtn);
        this.load.image('profile-window-footer', assets.profileWindowFooter);
        this.load.image('profile-window-header', assets.profileWindowHeader);
        this.load.image('profile-window-level', assets.profileWindowLevel);
        this.load.image('profile-window-bg', assets.profileWindowBg);
        this.load.image('profile-window-button-yellow', assets.profileWindowBtnYellow);
        this.load.image('profile-window-button-red', assets.profileWindowBtnRed);
        this.load.image('profile-window-button-green', assets.profileWindowBtnGreen);
        this.load.image('profile-window-button-blue', assets.profileWindowBtnBlue);
        this.load.image('profile-window-edit-avatar-btn', assets.profileWindowEitAvatarBtn);
        this.load.image('clan-window-search-plate-ns', assets.clanWindowSearchPlate);
        this.load.image('profile-window-line', assets.profileWindowLine);
        this.load.image('close-window-btn', assets.closeWindowBtn);
        this.load.image('avatar-1', assets.avatar1);
        this.load.image('avatar-2', assets.avatar2);
        this.load.image('avatar-3', assets.avatar3);
        this.load.image('avatar-4', assets.avatar4);
        this.load.image('avatar-5', assets.avatar5);
        this.load.image('avatar-6', assets.avatar6);
        if ((this.state.platform === 'vk' || this.state.platform === 'ok' || this.state.platform === 'ya') && this.state.avatar !== '') {
          this.load.image(`avatar-${this.state.user.id}`, this.state.avatar);
        }
        break;
      case 16: 
        this.load.image('settings-window-header', assets.settingsWindowHeader);
        this.load.image('settings-window-minus', assets.settingsWindowMinus);
        this.load.image('settings-window-plus', assets.settingsWindowPlus);
        this.load.image('settings-window-segment', assets.settingsWindowSegment);
        this.load.image('settings-window-music-plate', assets.settingsWindowMusicPlate);
        this.load.image('settings-window-sound-plate', assets.settingsWindowSoundPlate);
        this.load.image('close-window-btn', assets.closeWindowBtn);
        break;
      case 17: 
      case 18:
      case 19:
      case 20:
        if ((this.state.platform === 'vk' || this.state.platform === 'ok' || this.state.platform === 'ya') && this.state.avatar !== '') {
          this.load.image(`avatar-${this.state.user.id}`, this.state.avatar);
        }
        this.load.image('avatar-0', assets.avatar0);
        this.load.image('avatar-1', assets.avatar1);
        this.load.image('avatar-2', assets.avatar2);
        this.load.image('avatar-3', assets.avatar3);
        this.load.image('avatar-4', assets.avatar4);
        this.load.image('avatar-5', assets.avatar5);
        this.load.image('avatar-6', assets.avatar6);
        this.load.image('avatar-7', assets.avatar7);
        this.load.image('avatar-8', assets.avatar8);
        this.load.image('icon-shop-sheep', assets.iconShopSheep);
        this.load.image('icon-shop-chicken', assets.iconShopChicken);
        this.load.image('icon-shop-cow', assets.iconShopCow); 
        this.load.image('modal-square-bg', assets.squareBg);
        this.load.image('clan-window-header', assets.clanWindowHeader);
        this.load.image('clan-window-tab-active', assets.clanWindowTabActive);
        this.load.image('clan-window-tab-disable', assets.clanWindowTabDisable);
        this.load.image('clan-window-tab-close', assets.clanWindowTabClose);
        this.load.image('clan-window-crown', assets.clanWindowCrown);
        this.load.image('clan-window-line', assets.clanWindowLine);
        this.load.image('close-window-btn', assets.closeWindowBtn);
        this.load.image('clan-window-medal-bronze', assets.clanWindowMedalBronze);
        this.load.image('clan-window-medal-gold', assets.clanWindowMedalGold);
        this.load.image('clan-window-medal-silver', assets.clanWindowMedalSilver);
        this.load.image('clan-window-medal', assets.clanWindowMedal);
        this.load.image('clan-window-medal-ns', assets.clanWindowMedal);
        this.load.image('clan-window-leader-plate', assets.clanWindowLeaderPlate);
        this.load.image('clan-window-leader-plate-2', assets.clanWindowLeaderPlate);
        this.load.image('clan-window-search-plate', assets.clanWindowSearchPlate);
        this.load.image('clan-window-points-bg', assets.clanWindowPointsBg);
        this.load.image('clan-window-wreath', assets.clanWindowWreath);
        this.load.image('clan-window-wreath-bg', assets.clanWindowBgWreath);
        this.load.image('clan-window-icon-1', assets.clanWindowIcon1);
        this.load.image('clan-window-icon-2', assets.clanWindowIcon2);
        this.load.image('clan-window-icon-3', assets.clanWindowIcon3);
        this.load.image('clan-window-icon-4', assets.clanWindowIcon4);
        this.load.image('clan-window-icon-5', assets.clanWindowIcon5);
        this.load.image('clan-window-exclude-button', assets.clanWindowExcludeBtn);
        this.load.image('clan-icon-1', assets.clanIcon1);
        this.load.image('clan-icon-2', assets.clanIcon2);
        this.load.image('clan-icon-3', assets.clanIcon3);
        this.load.image('clan-icon-4', assets.clanIcon4);
        this.load.image('clan-icon-5', assets.clanIcon5);
        this.load.image('clan-icon-6', assets.clanIcon6);
        this.load.image('clan-icon-7', assets.clanIcon7);
        this.load.image('clan-icon-8', assets.clanIcon8);
        this.load.image('clan-icon-9', assets.clanIcon9);
        this.load.image('clan-icon-10', assets.clanIcon10);
        this.load.image('clan-icon-11', assets.clanIcon11);
        this.load.image('clan-icon-12', assets.clanIcon12);
        this.load.image('clan-frame-1', assets.clanFrame1);
        this.load.image('clan-frame-1', assets.clanFrame1);
        this.load.image('clan-frame-2', assets.clanFrame2);
        this.load.image('clan-frame-3', assets.clanFrame3);
        this.load.image('clan-frame-4', assets.clanFrame4);
        this.load.image('clan-frame-5', assets.clanFrame5);
        this.load.image('clan-frame-6', assets.clanFrame6);
        this.load.image('clan-frame-7', assets.clanFrame7);
        this.load.image('clan-frame-8', assets.clanFrame8);
        this.load.image('clan-frame-9', assets.clanFrame9);
        this.load.image('clan-frame-10', assets.clanFrame10);
        this.load.image('clan-frame-11', assets.clanFrame11);
        this.load.image('clan-bg-1', assets.clanBg1);
        this.load.image('clan-bg-2', assets.clanBg2);
        this.load.image('clan-bg-3', assets.clanBg3);
        this.load.image('clan-bg-4', assets.clanBg4);
        this.load.image('clan-bg-5', assets.clanBg5);
        this.load.image('clan-bg-6', assets.clanBg6);
        this.load.image('clan-bg-7', assets.clanBg7);
        this.load.image('clan-bg-8', assets.clanBg8);
        this.load.image('clan-bg-9', assets.clanBg9);
        this.load.image('clan-bg-10', assets.clanBg10);
        this.load.image('clan-bg-11', assets.clanBg11);
        this.load.image('clan-bg-12', assets.clanBg12);
        this.load.image('clan-bg-13', assets.clanBg13);
        this.load.image('clan-bg-14', assets.clanBg14);
        this.load.image('clan-main-frame', assets.clanMainFrame);
        this.load.image('clan-window-search-plate-ns', assets.clanWindowSearchPlate);
        this.load.image('clan-window-leader-plate-ns', assets.clanWindowLeaderPlate);
        this.load.image('clan-bank-sheep-package-1', assets.clanBankSheepPackage1);
        this.load.image('clan-bank-sheep-package-2', assets.clanBankSheepPackage2);
        this.load.image('clan-bank-sheep-package-3', assets.clanBankSheepPackage3);
        this.load.image('clan-bank-sheep-package-4', assets.clanBankSheepPackage4);
        this.load.image('clan-bank-chicken-package-1', assets.clanBankChickenPackage1);
        this.load.image('clan-bank-chicken-package-2', assets.clanBankChickenPackage2);
        this.load.image('clan-bank-chicken-package-3', assets.clanBankChickenPackage3);
        this.load.image('clan-bank-chicken-package-4', assets.clanBankChickenPackage4);
        this.load.image('clan-bank-cow-package-1', assets.clanBankCowPackage1);
        this.load.image('clan-bank-cow-package-2', assets.clanBankCowPackage2);
        this.load.image('clan-bank-cow-package-3', assets.clanBankCowPackage3);
        this.load.image('clan-bank-cow-package-4', assets.clanBankCowPackage4);
        this.load.image('clan-bank-diamond-package-1', assets.clanBankDiamondPackage1);
        this.load.image('clan-bank-diamond-package-2', assets.clanBankDiamondPackage2);
        this.load.image('clan-bank-diamond-package-3', assets.clanBankDiamondPackage3);
        this.load.image('clan-bank-diamond-package-4', assets.clanBankDiamondPackage4);
        this.load.image('icon-clan-sheep', assets.iconClanSheep);
        this.load.image('icon-clan-chicken', assets.iconClanChicken);
        this.load.image('icon-clan-cow', assets.iconClanCow);
        this.load.image('modal-header-orange', assets.headerOrange);
        this.load.image('tasks-top', assets.tasksTop);
        this.load.image('tasks-middle', assets.tasksMiddle);
        this.load.image('tasks-bottom', assets.tasksBottom);
        this.load.image('tasks-complete', assets.tasksComplete);
        this.load.image('tasks-uncomplete', assets.tasksUncomplete);
        this.load.image('tasks-reward', assets.tasksReward);
        this.load.image('tasks-bar', assets.tasksBar);
        this.load.image('close-window-btn', assets.closeWindowBtn);
        this.load.image('part-progress', assets.partProgress);
        this.load.image('clan-task-icon-1', assets.clanTaskIcon1);
        this.load.image('clan-task-icon-2', assets.clanTaskIcon2);
        this.load.image('clan-task-icon-3', assets.clanTaskIcon3);
        this.load.image('clan-task-icon-4', assets.clanTaskIcon4);
        this.load.image('clan-task-icon-5', assets.clanTaskIcon5);
        this.load.image('clan-task-icon-6', assets.clanTaskIcon6);
        this.load.image('clan-task-icon-7', assets.clanTaskIcon7);
        this.load.image('clan-task-icon-8', assets.clanTaskIcon8);
        this.load.image('clan-task-icon-9', assets.clanTaskIcon9);
        this.load.image('clan-task-icon-10', assets.clanTaskIcon10);
        this.load.image('clan-task-icon-11', assets.clanTaskIcon11);
        this.load.image('clan-task-icon-12', assets.clanTaskIcon12);
        this.load.image('clan-task-icon-13', assets.clanTaskIcon13);
        this.load.image('clan-task-icon-14', assets.clanTaskIcon14);
        this.load.image('clan-task-icon-15', assets.clanTaskIcon15);
        this.load.image('clan-task-icon-16', assets.clanTaskIcon16);
        this.load.image('clan-task-icon-17', assets.clanTaskIcon17);
        this.load.image('clan-task-icon-18', assets.clanTaskIcon18);
        this.load.image('clan-task-icon-19', assets.clanTaskIcon19);
        this.load.image('clan-bank-button', assets.clanBankBtn);
        this.load.image('clan-tab-icon-sheep', assets.clanTabIconSheep);
        this.load.image('clan-tab-icon-chicken', assets.clanTabIconChicken);
        this.load.image('clan-tab-icon-cow', assets.clanTabIconCow);
        this.load.image('clan-tournament-header', assets.clanTournamentHeader);
        this.load.image('clan-tournament-decor', assets.clanTournamentDecor);
        this.load.image('clan-tournament-animal-bg', assets.clanTournamentAnimalBg);
        this.load.image('clan-tournament-plate-bg', assets.clanTournamentPlateBg);
        this.load.image('clan-sheep-1', assets.clanSheep1);
        this.load.image('clan-sheep-2', assets.clanSheep2);
        this.load.image('clan-sheep-3', assets.clanSheep3);
        this.load.image('clan-sheep-4', assets.clanSheep4);
        this.load.image('clan-sheep-5', assets.clanSheep5);
        this.load.image('clan-sheep-6', assets.clanSheep6);
        this.load.image('clan-sheep-7', assets.clanSheep7);
        this.load.image('clan-sheep-8', assets.clanSheep8);
        this.load.image('clan-sheep-9', assets.clanSheep9);
        this.load.image('clan-sheep-10', assets.clanSheep10);
        this.load.image('clan-sheep-11', assets.clanSheep11);
        this.load.image('clan-sheep-12', assets.clanSheep12);
        this.load.image('clan-chicken-1', assets.clanChicken1);
        this.load.image('clan-chicken-2', assets.clanChicken2);
        this.load.image('clan-chicken-3', assets.clanChicken3);
        this.load.image('clan-chicken-4', assets.clanChicken4);
        this.load.image('clan-chicken-5', assets.clanChicken5);
        this.load.image('clan-chicken-6', assets.clanChicken6);
        this.load.image('clan-chicken-7', assets.clanChicken7);
        this.load.image('clan-chicken-8', assets.clanChicken8);
        this.load.image('clan-chicken-9', assets.clanChicken9);
        this.load.image('clan-chicken-10', assets.clanChicken10);
        this.load.image('clan-chicken-11', assets.clanChicken11);
        this.load.image('clan-chicken-12', assets.clanChicken12);
        this.load.image('clan-cow-1', assets.clanCow1);
        this.load.image('clan-cow-2', assets.clanCow2);
        this.load.image('clan-cow-3', assets.clanCow3);
        this.load.image('clan-cow-4', assets.clanCow4);
        this.load.image('clan-cow-5', assets.clanCow5);
        this.load.image('clan-cow-6', assets.clanCow6);
        this.load.image('clan-cow-7', assets.clanCow7);
        this.load.image('clan-cow-8', assets.clanCow8);
        this.load.image('clan-cow-9', assets.clanCow9);
        this.load.image('clan-cow-10', assets.clanCow10);
        this.load.image('clan-cow-11', assets.clanCow11);
        this.load.image('clan-cow-12', assets.clanCow12);
        this.load.image('shop-btn', assets.shopBtn);
        this.load.image('shop-btn-disable', assets.shopBtnDisable);
        this.load.image('decor-left', assets.decor1);
        this.load.image('decor-right', assets.decor2);
        this.load.image('clan-star', assets.clanStar);
        break;
      case 22:
        this.load.image('modal-header-event-end', assets.headerEventEnd);
        this.load.image('clan-window-leader-plate-2', assets.clanWindowLeaderPlate);
        this.load.image('clan-window-line', assets.clanWindowLine);
        this.load.image('done-chapter-button', assets.doneChapterButton);
        this.load.image('clan-award-plate', assets.clanRewardPlate);
        this.load.image('decor-left', assets.decor1);
        this.load.image('decor-right', assets.decor2);
        this.load.image('clan-big-medal', assets.bigMedal);
        this.load.image('clan-big-star', assets.bigStar);
        this.load.image('clan-glow', assets.clanGlow);
        this.load.image('clan-building', assets.clanBuilding);
        this.load.image('circle', assets.circle);
        this.load.image('clan-diamond-coin', assets.clanDiamondCoin);
        break;
      case 23:
        this.load.image('sale-window-header', assets.saleWindowHeader);
        this.load.image('sale-window-flags', assets.saleWindowFlags);
        this.load.image('sale-window-double-count', assets.saleWindowDoubleCount);
        this.load.image('sale-window-half-price', assets.saleWindowHalfPrice);
        this.load.image('sale-window-header', assets.settingsWindowHeader);
        this.load.image('close-window-btn', assets.closeWindowBtn);
        this.load.image('sale-icon-chicken-collector-improve', assets.saleIconChickenCollectorImprove);
        this.load.image('sale-icon-chicken-collector-price', assets.saleIconChickenCollectorPrice);
        this.load.image('sale-icon-chicken-feed', assets.saleIconChickenFeed);
        this.load.image('sale-icon-chicken-herd', assets.saleIconChickenHerd);
        this.load.image('sale-icon-chicken-money', assets.saleIconChickenMoney);
        this.load.image('sale-icon-chicken-price', assets.saleIconChickenPrice);
        this.load.image('sale-icon-chicken-repository-improve', assets.saleIconChickenRepositoryImprove);
        this.load.image('sale-icon-clan', assets.saleIconClan);
        this.load.image('sale-icon-cow-collector-improve', assets.saleIconCowCollectorImprove);
        this.load.image('sale-icon-cow-collector-price', assets.saleIconCowCollectorPrice);
        this.load.image('sale-icon-cow-factory-improve', assets.saleIconCowFactoryImprove);
        this.load.image('sale-icon-cow-feed', assets.saleIconCowFeed);
        this.load.image('sale-icon-cow-herd', assets.saleIconCowHerd);
        this.load.image('sale-icon-cow-money', assets.saleIconCowMoney);
        this.load.image('sale-icon-cow-price', assets.saleIconCowPrice);
        this.load.image('sale-icon-cow-repository-improve', assets.saleIconCowRepositoryImprove);
        this.load.image('sale-icon-diamond-count', assets.saleIconDiamondCount);
        this.load.image('sale-icon-package-price', assets.saleIconPackagePrice);
        this.load.image('sale-icon-sheep-collector-improve', assets.saleIconSheepCollectorImprove);
        this.load.image('sale-icon-sheep-collector-price', assets.saleIconSheepCollectorPrice);
        this.load.image('sale-icon-sheep-feed', assets.saleIconSheepFeed);
        this.load.image('sale-icon-sheep-herd', assets.saleIconSheepHerd);
        this.load.image('sale-icon-sheep-money', assets.saleIconSheepMoney);
        this.load.image('sale-icon-sheep-price', assets.saleIconSheepPrice);
        this.load.image('sale-icon-sheep-repository-improve', assets.saleIconSheepRepositoryImprove);
        this.load.image('modal-bg-plate', assets.modalBgPlate);
        break;
      case 24:
        this.load.image('review-bg', assets.reviewBg);
        this.load.image('review-btn-like', assets.reviewBtnLike);
        this.load.image('review-btn-dislike', assets.reviewBtnDislike);
        break;
      case 25:
        this.load.image('profile-window-header', assets.profileWindowHeader);
        this.load.image('profile-window-bg', assets.profileWindowBg);
        this.load.image('profile-window-level', assets.profileWindowBg);
        this.load.image('avatar-0', assets.avatar0);
        this.load.image('avatar-1', assets.avatar1);
        this.load.image('avatar-2', assets.avatar2);
        this.load.image('avatar-3', assets.avatar3);
        this.load.image('avatar-4', assets.avatar4);
        this.load.image('avatar-5', assets.avatar5);
        this.load.image('avatar-6', assets.avatar6);
        this.load.image('avatar-7', assets.avatar7);
        this.load.image('avatar-8', assets.avatar8);
        this.load.image('buy-avatar-plate', assets.buyPlate);
        this.load.image('avatar-frame', assets.avatarFrame);
        break;
      case 26:
        this.load.image('achievement-bg', assets.achievementBg);
        this.load.image('achievement-bg-complete', assets.achievementBgComplete);
        this.load.image('achievement-frame', assets.achievementFrame);
        this.load.image('achievement-window-header', assets.achievementHeader);
        Object.keys(assets.iconsUrl).forEach(key => {
          if (key.includes('ach')) this.load.image(`${key}-status`, assets.iconsUrl[key]);
        });
        break;
      case 27:
        this.load.image('settings-plate', assets.settingsPlate);
        this.load.image('clear-plate', assets.clearPlate);
        break;
      default:
        break;
    }
    
}