import { tabActiveAtlas, tabAtlas } from "../../atlases";

const partProgress: string = require("./../../../assets/images/modal/part-progress.png");
const newbieBg: string = require("./../../../assets/images/modal/daily/newbie-bg.png");
const newbieDay0: string = require("./../../../assets/images/modal/daily/newbie-day-0.png");
const newbieDay1: string = require("./../../../assets/images/modal/daily/newbie-day-1.png");
const newbieDay2: string = require("./../../../assets/images/modal/daily/newbie-day-2.png");
const newbieDay3: string = require("./../../../assets/images/modal/daily/newbie-day-3.png");
const newbieDay4: string = require("./../../../assets/images/modal/daily/newbie-day-4.png");
const newbieDay5: string = require("./../../../assets/images/modal/daily/newbie-day-5.png");
const newbieDay6: string = require("./../../../assets/images/modal/daily/newbie-day-6.png");
const newbieDay7: string = require("./../../../assets/images/modal/daily/newbie-day-7.png");
const dayYellow: string = require("./../../../assets/images/modal/daily/day-yellow.png");
const dayPurple: string = require("./../../../assets/images/modal/daily/day-purple.png");
const dayRed: string = require("./../../../assets/images/modal/daily/day-red.png");
const awardReceived: string = require("./../../../assets/images/modal/daily/award-received.png");
const donateBg: string = require("./../../../assets/images/modal/donate.png");
const doneChapterButton: string = require("./../../../assets/images/modal/done-chapter-button.png");
const dailyBg: string = require("./../../../assets/images/modal/daily-bg.png");
const middleButton: string = require("./../../../assets/images/modal/middle-button.png");
const sysSwitch: string = require("./../../../assets/images/modal/sys-switch.png");
const awardBg: string = require("./../../../assets/images/icons/award-bg.png");
const achievementDaily: string = require("./../../../assets/images/modal/achievement-daily.png");
const flashDaily: string = require("./../../../assets/images/modal/flash-daily.png");
const award3: string = require("./../../../assets/images/icons/award-3.png");
const award4: string = require("./../../../assets/images/icons/award-4.png");
const award5: string = require("./../../../assets/images/icons/award-5.png");
const doneChapter: string = require("./../../../assets/images/modal/done-chapter.png");
const pbChapterAnimal: string = require("./../../../assets/images/modal/pb-chapter-modal.png");
const greenProgress: string = require("./../../../assets/images/modal/green-progress.png");
const farmer: string = require("./../../../assets/images/farmer.png");
const tasksTop: string = require("./../../../assets/images/modal/tasks/top.png");
const tasksMiddle: string = require("./../../../assets/images/modal/tasks/middle.png");
const tasksBottom: string = require("./../../../assets/images/modal/tasks/bottom.png");
const tasksComplete: string = require("./../../../assets/images/modal/tasks/complete.png");
const tasksUncomplete: string = require("./../../../assets/images/modal/tasks/uncomplete.png");
const tasksReward: string = require("./../../../assets/images/modal/tasks/reward.png");
const tasksBar: string = require("./../../../assets/images/modal/tasks/bar.png");
const closeWindowBtn: string = require("./../../../assets/images/modal/close-window-btn.png");
const socialTaskBg: string = require("./../../../assets/images/modal/social-task/bg.png");
const socialTaskTop: string = require("./../../../assets/images/modal/social-task/top.png");
const socialTaskBottom: string = require("./../../../assets/images/modal/social-task/bottom.png");
const socialTaskMiddle: string = require("./../../../assets/images/modal/social-task/middle.png");
const bigButtonGrey: string = require("./../../../assets/images/modal/btn_l_lock.png");
const bigButtonBlue: string = require("./../../../assets/images/modal/btn_lb.png");
const bigButtonOrange: string = require("./../../../assets/images/modal/btn_lo.png");
const bigButtonRed: string = require("./../../../assets/images/modal/btn_lr.png");
const bigButtonYellow: string = require("./../../../assets/images/modal/btn_ly.png");
const repositorySellBtn: string = require("./../../../assets/images/modal/repository-sell-btn.png");
const herdBoostRoadSheep: string = require("./../../../assets/images/sheep/herd-boost-road-sheep.png");
const herdBoostRoadChicken: string = require("./../../../assets/images/chicken/herd-boost-road-chicken.png");
const herdBoostRoadCow: string = require("./../../../assets/images/cow/herd-boost-road-cow.png");
const herdBoostRoadEvent: string = require("./../../../assets/images/event/herd-boost-road-event.png");
const badMergingAnimation: string = require("./../../../assets/images/bad-merging-animation.png");
const boostWindowBg: string = require("./../../../assets/images/modal/herd-boost/background.png");
const boostCountdown: string = require("./../../../assets/images/modal/herd-boost/countdown.png");
const boostLeaves: string = require("./../../../assets/images/modal/herd-boost/leaves.png");
const flags: string = require("./../../../assets/images/modal/flags.png");
const chatBackground: string = require("./../../../assets/images/modal/chat/bg.png");
const chatDeleteBg: string = require("./../../../assets/images/modal/chat/delete-bg.png");
const chatTrash: string = require("./../../../assets/images/modal/chat/trash.png");
const chatArrow: string = require("./../../../assets/images/modal/chat/arrow.png");
const chatTab: string = require('./../../../assets/images/modal/chat/tab.png');
const chatTabClose: string = require('./../../../assets/images/modal/chat/tab-close.png');
const chatForeignMessageBg: string = require('./../../../assets/images/modal/chat/foreign-message-bg.png');
const chatClanMessageBg: string = require('./../../../assets/images/modal/chat/clan-message-bg.png');
const chatAdminMessageBg: string = require('./../../../assets/images/modal/chat/admin-message-bg.png');
const chatUserMessageBg: string = require('./../../../assets/images/modal/chat/user-message-bg.png');
const chatTabActive: string = require('./../../../assets/images/modal/chat/tab-active.png');
const chatInput: string = require('./../../../assets/images/modal/chat/input.png');
const chatSendBtn: string = require("./../../../assets/images/modal/chat/send-btn.png");
const chatEmojiBtn: string = require("./../../../assets/images/modal/chat/emoji-btn.png");
const autoprogressBG: string = require("./../../../assets/images/event/modal/autoprogress-bg.png");
const purpleBtn: string = require("./../../../assets/images/event/modal/purple-btn.png");
const ratingBG: string = require("./../../../assets/images/event/modal/rating-bg.png");
const shopBtn: string = require("./../../../assets/images/modal/shop-btn.png");
const shopBtnDisable: string = require("./../../../assets/images/modal/shop-btn-disable.png");
const ratingRulesBtn: string = require("./../../../assets/images/event/modal/rating-rules-btn.png");
const ratingPriseBtn: string = require("./../../../assets/images/event/modal/rating-price-btn.png");
const ratingPrisePlaces: string = require("./../../../assets/images/event/modal/rating-places.png");
const ratingBGAfter: string = require("./../../../assets/images/event/modal/raiting-bg-after.png");
const unicornStatus: string = require("./../../../assets/images/icons/unicorn-status.png");
const feedBoostChickenIcon: string = require("./../../../assets/images/icons/chicken-feed-boost.png");
const feedBoostCowIcon: string = require("./../../../assets/images/icons/cow-feed-boost.png");
const factoryWindow: string = require('./../../../assets/images/cow/modal/factory-window.png');
const factoryWheel: string = require('./../../../assets/images/cow/modal/factory-wheel.png');
const factoryProduction1: string = require('./../../../assets/images/cow/modal/factory-resource-1.png');
const factoryProduction2: string = require('./../../../assets/images/cow/modal/factory-resource-2.png');
const factoryProduction3: string = require('./../../../assets/images/cow/modal/factory-resource-3.png');
const factoryProduction4: string = require('./../../../assets/images/cow/modal/factory-resource-4.png');
const factoryCacao: string = require('./../../../assets/images/cow/modal/factory-cacao.png');
const factoryProductionSlot2: string = require('./../../../assets/images/cow/modal/factory-resource-slot-2.png');
const factoryProductionSlotDisable2: string = require('./../../../assets/images/cow/modal/factory-resource-slot-disable-2.png');
const factoryProductionSlot3: string = require('./../../../assets/images/cow/modal/factory-resource-slot-3.png');
const factoryProductionSlotDisable3: string = require('./../../../assets/images/cow/modal/factory-resource-slot-disable-3.png');
const factoryProductionSlot4: string = require('./../../../assets/images/cow/modal/factory-resource-slot-4.png');
const factoryProductionSlotDisable4: string = require('./../../../assets/images/cow/modal/factory-resource-slot-disable-4.png');
const profileWindowBtnYellow: string = require('./../../../assets/images/modal/profile/button-yellow.png');
const profileWindowBtnRed: string = require('./../../../assets/images/modal/profile/button-red.png');
const profileWindowBtnGreen: string = require('./../../../assets/images/modal/profile/button-green.png');
const profileWindoweEitAvataBtn: string = require('../../../assets/images/modal/profile/edit-avatar-btn.png');
const profileWindowSettingsBtn: string = require('./../../../assets/images/modal/profile/settings-btn.png');
const profileWindowFooter: string = require('./../../../assets/images/modal/profile/footer.png');
const profileWindowHeader: string = require('./../../../assets/images/modal/profile/header.png');
const profileWindowLevel: string = require('./../../../assets/images/modal/profile/level.png');
const profileWindowBg: string = require('./../../../assets/images/modal/profile/plate.png');
const settingsWindowHeader: string = require('./../../../assets/images/modal/settings/header.png');
const settingsWindowMinus: string = require('./../../../assets/images/modal/settings/minus.png');
const settingsWindowPlus: string = require('./../../../assets/images/modal/settings/plus.png');
const settingsWindowSegment: string = require('./../../../assets/images/modal/settings/segment.png');
const settingsWindowMusicPlate: string = require('./../../../assets/images/modal/settings/music-plate.png');
const settingsWindowSoundPlate: string = require('./../../../assets/images/modal/settings/sound-plate.png');
const squareBg: string = require('../../../assets/images/modal/square-bg.png');
const clanWindowHeader: string = require('../../../assets/images/modal/clan/header.png');
const clanWindowTabActive: string = require('../../../assets/images/modal/clan/tab-active.png');
const clanWindowTabDisable: string = require('../../../assets/images/modal/clan/tab-disable.png');
const clanWindowTabClose: string = require('../../../assets/images/modal/clan/tab-close.png');
const clanWindowCrown: string = require('../../../assets/images/modal/clan/сrown.png');
const clanWindowLine: string = require('../../../assets/images/modal/clan/line.png');
const clanWindowMedalBronze: string = require('../../../assets/images/modal/clan/medal-bronze.png');
const clanWindowMedalGold: string = require('../../../assets/images/modal/clan/medal-gold.png');
const clanWindowMedalSilver: string = require('../../../assets/images/modal/clan/medal-silver.png');
const clanWindowMedal: string = require('../../../assets/images/modal/clan/medal.png');
const clanWindowLeaderPlate: string = require('../../../assets/images/modal/clan/leader-plate.png');
const clanWindowSearchPlate: string = require('../../../assets/images/modal/clan/search-plate.png');
const clanWindowPointsBg: string = require('../../../assets/images/modal/clan/points-bg.png');
const clanWindowWreath: string = require('../../../assets/images/modal/clan/wreath.png');
const clanWindowBgWreath: string = require('../../../assets/images/modal/clan/bg-wreath.png');
const clanWindowIcon1: string = require('../../../assets/images/modal/clan/icon-1.png');
const clanWindowIcon2: string = require('../../../assets/images/modal/clan/icon-2.png');
const clanWindowIcon3: string = require('../../../assets/images/modal/clan/icon-3.png');
const clanWindowIcon4: string = require('../../../assets/images/modal/clan/icon-4.png');
const clanWindowIcon5: string = require('../../../assets/images/modal/clan/icon-5.png');
const clanWindowExcludeBtn: string = require('../../../assets/images/modal/clan/exclude-button.png');
const clanBg1: string = require('../../../assets/images/modal/clan/icon/bg-1.png');
const clanBg2: string = require('../../../assets/images/modal/clan/icon/bg-2.png');
const clanBg3: string = require('../../../assets/images/modal/clan/icon/bg-3.png');
const clanBg4: string = require('../../../assets/images/modal/clan/icon/bg-4.png');
const clanBg5: string = require('../../../assets/images/modal/clan/icon/bg-5.png');
const clanBg6: string = require('../../../assets/images/modal/clan/icon/bg-6.png');
const clanBg7: string = require('../../../assets/images/modal/clan/icon/bg-7.png');
const clanBg8: string = require('../../../assets/images/modal/clan/icon/bg-8.png');
const clanBg9: string = require('../../../assets/images/modal/clan/icon/bg-9.png');
const clanBg10: string = require('../../../assets/images/modal/clan/icon/bg-10.png');
const clanBg11: string = require('../../../assets/images/modal/clan/icon/bg-11.png');
const clanBg12: string = require('../../../assets/images/modal/clan/icon/bg-12.png');
const clanBg13: string = require('../../../assets/images/modal/clan/icon/bg-13.png');
const clanBg14: string = require('../../../assets/images/modal/clan/icon/bg-14.png');
const clanFrame1: string = require('../../../assets/images/modal/clan/icon/frame-1.png');
const clanFrame2: string = require('../../../assets/images/modal/clan/icon/frame-2.png');
const clanFrame3: string = require('../../../assets/images/modal/clan/icon/frame-3.png');
const clanFrame4: string = require('../../../assets/images/modal/clan/icon/frame-4.png');
const clanFrame5: string = require('../../../assets/images/modal/clan/icon/frame-5.png');
const clanFrame6: string = require('../../../assets/images/modal/clan/icon/frame-6.png');
const clanFrame7: string = require('../../../assets/images/modal/clan/icon/frame-7.png');
const clanFrame8: string = require('../../../assets/images/modal/clan/icon/frame-8.png');
const clanFrame9: string = require('../../../assets/images/modal/clan/icon/frame-9.png');
const clanFrame10: string = require('../../../assets/images/modal/clan/icon/frame-10.png');
const clanFrame11: string = require('../../../assets/images/modal/clan/icon/frame-11.png');
const clanIcon1: string = require('../../../assets/images/modal/clan/icon/icon-1.png');
const clanIcon2: string = require('../../../assets/images/modal/clan/icon/icon-2.png');
const clanIcon3: string = require('../../../assets/images/modal/clan/icon/icon-3.png');
const clanIcon4: string = require('../../../assets/images/modal/clan/icon/icon-4.png');
const clanIcon5: string = require('../../../assets/images/modal/clan/icon/icon-5.png');
const clanIcon6: string = require('../../../assets/images/modal/clan/icon/icon-6.png');
const clanIcon7: string = require('../../../assets/images/modal/clan/icon/icon-7.png');
const clanIcon8: string = require('../../../assets/images/modal/clan/icon/icon-8.png');
const clanIcon9: string = require('../../../assets/images/modal/clan/icon/icon-9.png');
const clanIcon10: string = require('../../../assets/images/modal/clan/icon/icon-10.png');
const clanIcon11: string = require('../../../assets/images/modal/clan/icon/icon-11.png');
const clanIcon12: string = require('../../../assets/images/modal/clan/icon/icon-12.png');
const clanMainFrame: string = require('../../../assets/images/modal/clan/icon/main-frame.png');
const iconShopSheep: string = require("../../../assets/images/sheep/icons/icon-shop-sheep.png");
const iconShopChicken: string = require("../../../assets/images/chicken/icons/icon-shop-chicken.png");
const iconShopCow: string = require("../../../assets/images/cow/icons/icon-shop-cow.png");
const clanBankSheepPackage1: string = require('../../../assets/images/modal/clan/bank/sheep-1.png');
const clanBankSheepPackage2: string = require('../../../assets/images/modal/clan/bank/sheep-2.png');
const clanBankSheepPackage3: string = require('../../../assets/images/modal/clan/bank/sheep-3.png');
const clanBankSheepPackage4: string = require('../../../assets/images/modal/clan/bank/sheep-4.png');
const clanBankChickenPackage1: string = require('../../../assets/images/modal/clan/bank/chicken-1.png');
const clanBankChickenPackage2: string = require('../../../assets/images/modal/clan/bank/chicken-2.png');
const clanBankChickenPackage3: string = require('../../../assets/images/modal/clan/bank/chicken-3.png');
const clanBankChickenPackage4: string = require('../../../assets/images/modal/clan/bank/chicken-4.png');
const clanBankCowPackage1: string = require('../../../assets/images/modal/clan/bank/cow-1.png');
const clanBankCowPackage2: string = require('../../../assets/images/modal/clan/bank/cow-2.png');
const clanBankCowPackage3: string = require('../../../assets/images/modal/clan/bank/cow-3.png');
const clanBankCowPackage4: string = require('../../../assets/images/modal/clan/bank/cow-4.png');
const clanBankDiamondPackage1: string = require('../../../assets/images/modal/clan/bank/diamond-1.png');
const clanBankDiamondPackage2: string = require('../../../assets/images/modal/clan/bank/diamond-2.png');
const clanBankDiamondPackage3: string = require('../../../assets/images/modal/clan/bank/diamond-3.png');
const clanBankDiamondPackage4: string = require('../../../assets/images/modal/clan/bank/diamond-4.png');
const iconClanSheep: string = require('../../../assets/images/icons/clan-sheep.png');
const iconClanChicken: string = require('../../../assets/images/icons/clan-chicken.png');
const iconClanCow: string = require('../../../assets/images/icons/clan-cow.png');
const headerOrange: string = require('../../../assets/images/modal/header-orange.png');
const headerEventEnd: string = require('../../../assets/images/modal/clan/header-event-end.png');
const clanRewardPlate: string = require('../../../assets/images/modal/clan/clan-reward-plate.png');
const decor1: string = require('../../../assets/images/modal/clan/decor-1.png');
const decor2: string = require('../../../assets/images/modal/clan/decor-2.png');
const bigMedal: string = require('../../../assets/images/modal/clan/big-medal-event.png');
const bigStar: string = require('../../../assets/images/modal/clan/big-star-event.png');
const clanStar: string = require('../../../assets/images/modal/clan/star-event.png');
const clanGlow: string = require('../../../assets/images/modal/clan/glow.png');
const clanBuilding: string = require('../../../assets/images/clan/clan-building.png');
const circle: string = require("./../../../assets/images/circle.png");
const clanTaskIcon1: string = require('../../../assets/images/modal/clan/tasks/task-1.png');
const clanTaskIcon2: string = require('../../../assets/images/modal/clan/tasks/task-2.png');
const clanTaskIcon3: string = require('../../../assets/images/modal/clan/tasks/task-3.png');
const clanTaskIcon4: string = require('../../../assets/images/modal/clan/tasks/task-4.png');
const clanTaskIcon5: string = require('../../../assets/images/modal/clan/tasks/task-5.png');
const clanTaskIcon6: string = require('../../../assets/images/modal/clan/tasks/task-6.png');
const clanTaskIcon7: string = require('../../../assets/images/modal/clan/tasks/task-7.png');
const clanTaskIcon8: string = require('../../../assets/images/modal/clan/tasks/task-8.png');
const clanTaskIcon9: string = require('../../../assets/images/modal/clan/tasks/task-9.png');
const clanTaskIcon10: string = require('../../../assets/images/modal/clan/tasks/task-10.png');
const clanTaskIcon11: string = require('../../../assets/images/modal/clan/tasks/task-11.png');
const clanTaskIcon12: string = require('../../../assets/images/modal/clan/tasks/task-12.png');
const clanTaskIcon13: string = require('../../../assets/images/modal/clan/tasks/task-13.png');
const clanTaskIcon14: string = require('../../../assets/images/modal/clan/tasks/task-14.png');
const clanTaskIcon15: string = require('../../../assets/images/modal/clan/tasks/task-15.png');
const clanTaskIcon16: string = require('../../../assets/images/modal/clan/tasks/task-16.png');
const clanTaskIcon17: string = require('../../../assets/images/modal/clan/tasks/task-17.png');
const clanTaskIcon18: string = require('../../../assets/images/modal/clan/tasks/task-18.png');
const clanTaskIcon19: string = require('../../../assets/images/modal/clan/tasks/task-19.png');
const clanBankBtn: string = require('../../../assets/images/modal/clan/bank-btn.png');
const clanTabIconSheep: string = require('../../../assets/images/modal/clan/icon-tab-sheep.png');
const clanTabIconChicken: string = require('../../../assets/images/modal/clan/icon-tab-chicken.png');
const clanTabIconCow: string = require('../../../assets/images/modal/clan/icon-tab-cow.png');
const clanTournamentHeader: string = require('../../../assets/images/modal/clan/tournament/header.png');
const clanTournamentDecor: string = require('../../../assets/images/modal/clan/tournament/decor.png');
const clanTournamentAnimalBg: string = require('../../../assets/images/modal/clan/tournament/animal-bg.png');
const clanTournamentPlateBg: string = require('../../../assets/images/modal/clan/tournament/plate-bg.png');
const clanSheep1: string = require('../../../assets/images/clan/animals/sheep-1.png');
const clanSheep2: string = require('../../../assets/images/clan/animals/sheep-2.png');
const clanSheep3: string = require('../../../assets/images/clan/animals/sheep-3.png');
const clanSheep4: string = require('../../../assets/images/clan/animals/sheep-4.png');
const clanSheep5: string = require('../../../assets/images/clan/animals/sheep-5.png');
const clanSheep6: string = require('../../../assets/images/clan/animals/sheep-6.png');
const clanSheep7: string = require('../../../assets/images/clan/animals/sheep-7.png');
const clanSheep8: string = require('../../../assets/images/clan/animals/sheep-8.png');
const clanSheep9: string = require('../../../assets/images/clan/animals/sheep-9.png');
const clanSheep10: string = require('../../../assets/images/clan/animals/sheep-10.png');
const clanSheep11: string = require('../../../assets/images/clan/animals/sheep-11.png');
const clanSheep12: string = require('../../../assets/images/clan/animals/sheep-12.png');
const clanChicken1: string = require('../../../assets/images/clan/animals/chicken-1.png');
const clanChicken2: string = require('../../../assets/images/clan/animals/chicken-2.png');
const clanChicken3: string = require('../../../assets/images/clan/animals/chicken-3.png');
const clanChicken4: string = require('../../../assets/images/clan/animals/chicken-4.png');
const clanChicken5: string = require('../../../assets/images/clan/animals/chicken-5.png');
const clanChicken6: string = require('../../../assets/images/clan/animals/chicken-6.png');
const clanChicken7: string = require('../../../assets/images/clan/animals/chicken-7.png');
const clanChicken8: string = require('../../../assets/images/clan/animals/chicken-8.png');
const clanChicken9: string = require('../../../assets/images/clan/animals/chicken-9.png');
const clanChicken10: string = require('../../../assets/images/clan/animals/chicken-10.png');
const clanChicken11: string = require('../../../assets/images/clan/animals/chicken-11.png');
const clanChicken12: string = require('../../../assets/images/clan/animals/chicken-12.png');
const clanCow1: string = require('../../../assets/images/clan/animals/cow-1.png');
const clanCow2: string = require('../../../assets/images/clan/animals/cow-2.png');
const clanCow3: string = require('../../../assets/images/clan/animals/cow-3.png');
const clanCow4: string = require('../../../assets/images/clan/animals/cow-4.png');
const clanCow5: string = require('../../../assets/images/clan/animals/cow-5.png');
const clanCow6: string = require('../../../assets/images/clan/animals/cow-6.png');
const clanCow7: string = require('../../../assets/images/clan/animals/cow-7.png');
const clanCow8: string = require('../../../assets/images/clan/animals/cow-8.png');
const clanCow9: string = require('../../../assets/images/clan/animals/cow-9.png');
const clanCow10: string = require('../../../assets/images/clan/animals/cow-10.png');
const clanCow11: string = require('../../../assets/images/clan/animals/cow-11.png');
const clanCow12: string = require('../../../assets/images/clan/animals/cow-12.png');
const clanDiamondCoin: string = require('../../../assets/images/clan/coin-diamond.png');

const saleWindowHeader: string = require('./../../../assets/images/modal/sale/header.png');
const saleWindowFlags: string = require('./../../../assets/images/modal/sale/flags.png');
const saleWindowDoubleCount: string = require('../../../assets/images/modal/sale/sale-2.png');
const saleWindowHalfPrice: string = require('../../../assets/images/modal/sale/sale-1.png');
const saleIconChickenCollectorImprove: string = require('../../../assets/images/modal/sale/icons/chicken-collector-improve.png');
const saleIconChickenCollectorPrice: string = require('../../../assets/images/modal/sale/icons/chicken-collector-price.png');
const saleIconChickenFeed: string = require('../../../assets/images/modal/sale/icons/chicken-feed.png');
const saleIconChickenHerd: string = require('../../../assets/images/modal/sale/icons/chicken-herd.png');
const saleIconChickenMoney: string = require('../../../assets/images/modal/sale/icons/chicken-money.png');
const saleIconChickenPrice: string = require('../../../assets/images/modal/sale/icons/chicken-price.png');
const saleIconChickenRepositoryImprove: string = require('../../../assets/images/modal/sale/icons/chicken-repository-improve.png');
const saleIconClan: string = require('../../../assets/images/modal/sale/icons/clan.png');
const saleIconCowCollectorImprove: string = require('../../../assets/images/modal/sale/icons/cow-collector-improve.png');
const saleIconCowCollectorPrice: string = require('../../../assets/images/modal/sale/icons/cow-collector-price.png');
const saleIconCowFactoryImprove: string = require('../../../assets/images/modal/sale/icons/cow-factory-improve.png');
const saleIconCowFeed: string = require('../../../assets/images/modal/sale/icons/cow-feed.png');
const saleIconCowHerd: string = require('../../../assets/images/modal/sale/icons/cow-herd.png');
const saleIconCowMoney: string = require('../../../assets/images/modal/sale/icons/cow-money.png');
const saleIconCowPrice: string = require('../../../assets/images/modal/sale/icons/cow-price.png');
const saleIconCowRepositoryImprove: string = require('../../../assets/images/modal/sale/icons/cow-repository-improve.png');
const saleIconDiamondCount: string = require('../../../assets/images/modal/sale/icons/diamond-count.png');
const saleIconPackagePrice: string = require('../../../assets/images/modal/sale/icons/package-price.png');
const saleIconSheepCollectorImprove: string = require('../../../assets/images/modal/sale/icons/sheep-collector-improve.png');
const saleIconSheepCollectorPrice: string = require('../../../assets/images/modal/sale/icons/sheep-collector-price.png');
const saleIconSheepFeed: string = require('../../../assets/images/modal/sale/icons/sheep-feed.png');
const saleIconSheepHerd: string = require('../../../assets/images/modal/sale/icons/sheep-herd.png');
const saleIconSheepMoney: string = require('../../../assets/images/modal/sale/icons/sheep-money.png');
const saleIconSheepPrice: string = require('../../../assets/images/modal/sale/icons/sheep-price.png');
const saleIconSheepRepositoryImprove: string = require('../../../assets/images/modal/sale/icons/sheep-repository-improve.png');
const modalBgPlate: string = require('../../../assets/images/modal/bg-plate.png');
const reviewBg: string = require('../../../assets/images/modal/review/bg.png');
const reviewBtnLike: string = require('../../../assets/images/modal/review/btn-like.png');
const reviewBtnDislike: string = require('../../../assets/images/modal/review/btn-dislike.png');
const avatar0: string = require('../../../assets/images/avatars/avatar-0.png');
const avatar1: string = require('../../../assets/images/avatars/avatar-1.png');
const avatar2: string = require('../../../assets/images/avatars/avatar-2.png');
const avatar3: string = require('../../../assets/images/avatars/avatar-3.png');
const avatar4: string = require('../../../assets/images/avatars/avatar-4.png');
const avatar5: string = require('../../../assets/images/avatars/avatar-5.png');
const avatar6: string = require('../../../assets/images/avatars/avatar-6.png');
const avatar7: string = require('../../../assets/images/avatars/avatar-7.png');
const avatar8: string = require('../../../assets/images/avatars/avatar-8.png');
const buyPlate: string = require('../../../assets/images/modal/buy-plate.png');
const avatarFrame: string = require('../../../assets/images/modal/avatar-frame.png');
const achievementIcon1: string = require('../../../assets/images/achievements/icon-1.png');

export default function typePreload(): void {
    switch (this.state.modal.type) {
      case 1: // системное окно
        this.load.image('unicorn-status', unicornStatus);
        this.load.image('farmer', farmer);
        this.load.image('pb-chapter-modal', pbChapterAnimal);
        this.load.image('big-btn-grey', bigButtonGrey);
        this.load.image('big-btn-blue', bigButtonBlue);
        this.load.image('big-btn-orange', bigButtonOrange);
        this.load.image('big-btn-red', bigButtonRed);
        this.load.image('big-btn-yellow', bigButtonYellow);
        this.load.image('repository-sell-btn', repositorySellBtn);
        this.load.image('green-progress', greenProgress);
        this.load.image('middle-button', middleButton);    
        this.load.image('sys-switch', sysSwitch);
        break;
      case 2: // магазин
        // this.load.image('shop-window', shopWindow);
        if (this.state.farm === 'Chicken') this.load.image('chicken-feed-boost-icon', feedBoostChickenIcon); 
        else if (this.state.farm === 'Cow') this.load.image('cow-feed-boost-icon', feedBoostCowIcon); 
        
        break;
      case 3: // окно с заданиями
        this.load.image('tasks-top', tasksTop);
        this.load.image('tasks-middle', tasksMiddle);
        this.load.image('tasks-bottom', tasksBottom);
        this.load.image('tasks-uncomplete', tasksUncomplete);
        this.load.image('tasks-reward', tasksReward);
        this.load.image('tasks-bar', tasksBar);
        this.load.image('close-window-btn', closeWindowBtn);
        this.load.image('part-progress', partProgress);
        break;
      case 4: // ежедневные награды +
        this.load.image('award-bg', awardBg);
        this.load.image('daily-bg', dailyBg);
        this.load.image('achievement-daily', achievementDaily);
        this.load.image('flash-daily', flashDaily);
        this.load.image('middle-button', middleButton);
        this.load.image('award-3', award3);
        this.load.image('award-4', award4);
        this.load.image('award-5', award5);
        break;
      case 5: // следующая глава +
        this.load.image('done-chapter', doneChapter);
        this.load.image('done-chapter-button', doneChapterButton);

        break;
      case 6: // ежедневные награды новичков +
        this.load.image('newbie-bg', newbieBg);
        this.load.image('newbie-day-0', newbieDay0);
        this.load.image('newbie-day-1', newbieDay1);
        this.load.image('newbie-day-2', newbieDay2);
        this.load.image('newbie-day-3', newbieDay3);
        this.load.image('newbie-day-4', newbieDay4);
        this.load.image('newbie-day-5', newbieDay5);
        this.load.image('newbie-day-6', newbieDay6);
        this.load.image('newbie-day-7', newbieDay7);
        this.load.image('day-yellow', dayYellow);
        this.load.image('day-purple', dayPurple);
        this.load.image('day-red', dayRed);
        this.load.image('award-received', awardReceived);
        this.load.image('close-window-btn', closeWindowBtn);
        break;
      case 7: // окно выдачи донатных кристаллов +
        this.load.image('done-chapter-button', doneChapterButton);
        this.load.image('donate', donateBg);
        break;
      case 8: // окно стадного буста +
        if (this.state.farm === 'Sheep') this.load.image('herd-boost-road-sheep', herdBoostRoadSheep);
        if (this.state.farm === 'Chicken') this.load.image('herd-boost-road-chicken', herdBoostRoadChicken);
        if (this.state.farm === 'Cow') this.load.image('herd-boost-road-cow', herdBoostRoadCow);
        if (this.state.farm === 'Unicorn') this.load.image('herd-boost-road-unicorn', herdBoostRoadEvent);
        this.load.image('bad-merging-animation', badMergingAnimation);
        this.load.image('boost-window-bg', boostWindowBg);
        this.load.image('boost-countdown', boostCountdown);
        this.load.image('boost-leaves', boostLeaves);
        this.load.image('flags', flags);
        break;
      case 9: // Чат +
        this.load.image('chat-bg', chatBackground);
        this.load.image('chat-delete-bg', chatDeleteBg);
        this.load.image('chat-trash', chatTrash);
        this.load.image('chat-arrow', chatArrow);
        this.load.atlas('chat-tab', chatTab, tabAtlas);
        this.load.image('chat-foreign-message-bg', chatForeignMessageBg);
        this.load.image('chat-clan-message-bg', chatClanMessageBg);
        this.load.image('chat-admin-message-bg', chatAdminMessageBg);
        this.load.image('chat-user-message-bg', chatUserMessageBg);
        this.load.image('chat-tab-close', chatTabClose);
        this.load.atlas('chat-tab-active', chatTabActive, tabActiveAtlas);
        this.load.image('chat-input-bg', chatInput);
        this.load.image('chat-send-btn', chatSendBtn);
        this.load.image('chat-emoji-btn', chatEmojiBtn);
        this.load.image('unicorn-status', unicornStatus);
        this.load.image('profile-window-button-yellow', profileWindowBtnYellow);
        this.load.image('profile-window-button-red', profileWindowBtnRed);
        this.load.image('profile-window-button-green', profileWindowBtnGreen);
        break;
      case 10: // окно автопрогресса ивентовой фермы +
        this.load.image('autoprogress-bg', autoprogressBG);
        this.load.image('purple-btn', purpleBtn);
        break;
      case 11: // окно рейтингов ивентовой фермы +
        this.load.image('rating-bg', ratingBG);
        this.load.image('rating-rules-btn', ratingRulesBtn);
        this.load.image('rating-price-btn', ratingPriseBtn);
        this.load.image('rating-places', ratingPrisePlaces);
        this.load.image('unicorn-status', unicornStatus);
        this.load.image('close-window-btn', closeWindowBtn);
        break;
      case 12: // окно выдачи наград ивентовой фермы +
        this.load.image('raiting-bg-after',ratingBGAfter);
        this.load.image('rating-places', ratingPrisePlaces);
        this.load.image('rating-rules-btn', ratingRulesBtn);
        this.load.image('rating-price-btn', ratingPriseBtn);
        this.load.image('unicorn-status', unicornStatus);
        this.load.image('close-window-btn', closeWindowBtn);

        break;
      case 13:
        this.load.image('factory-window', factoryWindow);
        this.load.image('factory-wheel', factoryWheel);
        this.load.image('factory-production-1', factoryProduction1);
        this.load.image('factory-production-2', factoryProduction2);
        this.load.image('factory-production-3', factoryProduction3);
        this.load.image('factory-production-4', factoryProduction4);
        this.load.image('factory-cacao', factoryCacao);
        this.load.image('factory-production-slot-2', factoryProductionSlot2);
        this.load.image('factory-production-slot-disable-2', factoryProductionSlotDisable2);
        this.load.image('factory-production-slot-3', factoryProductionSlot3);
        this.load.image('factory-production-slot-disable-3', factoryProductionSlotDisable3);
        this.load.image('factory-production-slot-4', factoryProductionSlot4);
        this.load.image('factory-production-slot-disable-4', factoryProductionSlotDisable4);
        this.load.image('close-window-btn', closeWindowBtn);
        break;
      case 14: 
        this.load.image('social-task-bg', socialTaskBg);
        this.load.image('social-task-top', socialTaskTop);
        this.load.image('social-task-bottom', socialTaskBottom);
        this.load.image('social-task-middle', socialTaskMiddle);
        this.load.image('shop-btn', shopBtn);
        this.load.image('shop-btn-disable', shopBtnDisable);
        this.load.image('close-window-btn', closeWindowBtn);
        break;
      case 15: 
        this.load.image('profile-window-settings-btn', profileWindowSettingsBtn);
        this.load.image('profile-window-footer', profileWindowFooter);
        this.load.image('profile-window-header', profileWindowHeader);
        this.load.image('profile-window-level', profileWindowLevel);
        this.load.image('profile-window-bg', profileWindowBg);
        this.load.image('profile-window-button-yellow', profileWindowBtnYellow);
        this.load.image('profile-window-button-red', profileWindowBtnRed);
        this.load.image('profile-window-button-green', profileWindowBtnGreen);
        this.load.image('profile-window-edit-avatar-btn', profileWindoweEitAvataBtn);
        this.load.image('clan-window-search-plate-ns', clanWindowSearchPlate);
        this.load.image('close-window-btn', closeWindowBtn);
        this.load.image('avatar-1', avatar1);
        this.load.image('avatar-2', avatar2);
        this.load.image('avatar-3', avatar3);
        this.load.image('avatar-4', avatar4);
        this.load.image('avatar-5', avatar5);
        this.load.image('avatar-6', avatar6);
        if ((this.state.platform === 'vk' || this.state.platform === 'ok' || this.state.platform === 'ya') && this.state.avatar !== '') {
          this.load.image(`avatar-${this.state.user.id}`, this.state.avatar);
        }
        break;
      case 16: 
        this.load.image('settings-window-header', settingsWindowHeader);
        this.load.image('settings-window-minus', settingsWindowMinus);
        this.load.image('settings-window-plus', settingsWindowPlus);
        this.load.image('settings-window-segment', settingsWindowSegment);
        this.load.image('settings-window-music-plate', settingsWindowMusicPlate);
        this.load.image('settings-window-sound-plate', settingsWindowSoundPlate);
        this.load.image('close-window-btn', closeWindowBtn);
        break;
      case 17: 
      case 18:
      case 19:
      case 20:
        if ((this.state.platform === 'vk' || this.state.platform === 'ok' || this.state.platform === 'ya') && this.state.avatar !== '') {
          this.load.image(`avatar-${this.state.user.id}`, this.state.avatar);
        }
        this.load.image('avatar-0', avatar0);
        this.load.image('avatar-1', avatar1);
        this.load.image('avatar-2', avatar2);
        this.load.image('avatar-3', avatar3);
        this.load.image('avatar-4', avatar4);
        this.load.image('avatar-5', avatar5);
        this.load.image('avatar-6', avatar6);
        this.load.image('avatar-7', avatar7);
        this.load.image('avatar-8', avatar8);
        this.load.image('icon-shop-sheep', iconShopSheep);
        this.load.image('icon-shop-chicken', iconShopChicken);
        this.load.image('icon-shop-cow', iconShopCow); 
        this.load.image('modal-square-bg', squareBg);
        this.load.image('clan-window-header', clanWindowHeader);
        this.load.image('clan-window-tab-active', clanWindowTabActive);
        this.load.image('clan-window-tab-disable', clanWindowTabDisable);
        this.load.image('clan-window-tab-close', clanWindowTabClose);
        this.load.image('clan-window-crown', clanWindowCrown);
        this.load.image('clan-window-line', clanWindowLine);
        this.load.image('close-window-btn', closeWindowBtn);
        this.load.image('clan-window-medal-bronze', clanWindowMedalBronze);
        this.load.image('clan-window-medal-gold', clanWindowMedalGold);
        this.load.image('clan-window-medal-silver', clanWindowMedalSilver);
        this.load.image('clan-window-medal', clanWindowMedal);
        this.load.image('clan-window-medal-ns', clanWindowMedal);
        this.load.image('clan-window-leader-plate', clanWindowLeaderPlate);
        this.load.image('clan-window-leader-plate-2', clanWindowLeaderPlate);
        this.load.image('clan-window-search-plate', clanWindowSearchPlate);
        this.load.image('clan-window-points-bg', clanWindowPointsBg);
        this.load.image('clan-window-wreath', clanWindowWreath);
        this.load.image('clan-window-wreath-bg', clanWindowBgWreath);
        this.load.image('clan-window-icon-1', clanWindowIcon1);
        this.load.image('clan-window-icon-2', clanWindowIcon2);
        this.load.image('clan-window-icon-3', clanWindowIcon3);
        this.load.image('clan-window-icon-4', clanWindowIcon4);
        this.load.image('clan-window-icon-5', clanWindowIcon5);
        this.load.image('clan-window-exclude-button', clanWindowExcludeBtn);
        this.load.image('clan-icon-1', clanIcon1);
        this.load.image('clan-icon-2', clanIcon2);
        this.load.image('clan-icon-3', clanIcon3);
        this.load.image('clan-icon-4', clanIcon4);
        this.load.image('clan-icon-5', clanIcon5);
        this.load.image('clan-icon-6', clanIcon6);
        this.load.image('clan-icon-7', clanIcon7);
        this.load.image('clan-icon-8', clanIcon8);
        this.load.image('clan-icon-9', clanIcon9);
        this.load.image('clan-icon-10', clanIcon10);
        this.load.image('clan-icon-11', clanIcon11);
        this.load.image('clan-icon-12', clanIcon12);
        this.load.image('clan-frame-1', clanFrame1);
        this.load.image('clan-frame-1', clanFrame1);
        this.load.image('clan-frame-2', clanFrame2);
        this.load.image('clan-frame-3', clanFrame3);
        this.load.image('clan-frame-4', clanFrame4);
        this.load.image('clan-frame-5', clanFrame5);
        this.load.image('clan-frame-6', clanFrame6);
        this.load.image('clan-frame-7', clanFrame7);
        this.load.image('clan-frame-8', clanFrame8);
        this.load.image('clan-frame-9', clanFrame9);
        this.load.image('clan-frame-10', clanFrame10);
        this.load.image('clan-frame-11', clanFrame11);
        this.load.image('clan-bg-1', clanBg1);
        this.load.image('clan-bg-2', clanBg2);
        this.load.image('clan-bg-3', clanBg3);
        this.load.image('clan-bg-4', clanBg4);
        this.load.image('clan-bg-5', clanBg5);
        this.load.image('clan-bg-6', clanBg6);
        this.load.image('clan-bg-7', clanBg7);
        this.load.image('clan-bg-8', clanBg8);
        this.load.image('clan-bg-9', clanBg9);
        this.load.image('clan-bg-10', clanBg10);
        this.load.image('clan-bg-11', clanBg11);
        this.load.image('clan-bg-12', clanBg12);
        this.load.image('clan-bg-13', clanBg13);
        this.load.image('clan-bg-14', clanBg14);
        this.load.image('clan-main-frame',clanMainFrame);
        this.load.image('clan-window-search-plate-ns', clanWindowSearchPlate);
        this.load.image('clan-window-leader-plate-ns', clanWindowLeaderPlate);
        this.load.image('clan-bank-sheep-package-1', clanBankSheepPackage1);
        this.load.image('clan-bank-sheep-package-2', clanBankSheepPackage2);
        this.load.image('clan-bank-sheep-package-3', clanBankSheepPackage3);
        this.load.image('clan-bank-sheep-package-4', clanBankSheepPackage4);
        this.load.image('clan-bank-chicken-package-1', clanBankChickenPackage1);
        this.load.image('clan-bank-chicken-package-2', clanBankChickenPackage2);
        this.load.image('clan-bank-chicken-package-3', clanBankChickenPackage3);
        this.load.image('clan-bank-chicken-package-4', clanBankChickenPackage4);
        this.load.image('clan-bank-cow-package-1', clanBankCowPackage1);
        this.load.image('clan-bank-cow-package-2', clanBankCowPackage2);
        this.load.image('clan-bank-cow-package-3', clanBankCowPackage3);
        this.load.image('clan-bank-cow-package-4', clanBankCowPackage4);
        this.load.image('clan-bank-diamond-package-1', clanBankDiamondPackage1);
        this.load.image('clan-bank-diamond-package-2', clanBankDiamondPackage2);
        this.load.image('clan-bank-diamond-package-3', clanBankDiamondPackage3);
        this.load.image('clan-bank-diamond-package-4', clanBankDiamondPackage4);
        this.load.image('icon-clan-sheep', iconClanSheep);
        this.load.image('icon-clan-chicken', iconClanChicken);
        this.load.image('icon-clan-cow', iconClanCow);
        this.load.image('modal-header-orange', headerOrange);
        this.load.image('tasks-top', tasksTop);
        this.load.image('tasks-middle', tasksMiddle);
        this.load.image('tasks-bottom', tasksBottom);
        this.load.image('tasks-complete', tasksComplete);
        this.load.image('tasks-uncomplete', tasksUncomplete);
        this.load.image('tasks-reward', tasksReward);
        this.load.image('tasks-bar', tasksBar);
        this.load.image('close-window-btn', closeWindowBtn);
        this.load.image('part-progress', partProgress);
        this.load.image('clan-task-icon-1', clanTaskIcon1);
        this.load.image('clan-task-icon-2', clanTaskIcon2);
        this.load.image('clan-task-icon-3', clanTaskIcon3);
        this.load.image('clan-task-icon-4', clanTaskIcon4);
        this.load.image('clan-task-icon-5', clanTaskIcon5);
        this.load.image('clan-task-icon-6', clanTaskIcon6);
        this.load.image('clan-task-icon-7', clanTaskIcon7);
        this.load.image('clan-task-icon-8', clanTaskIcon8);
        this.load.image('clan-task-icon-9', clanTaskIcon9);
        this.load.image('clan-task-icon-10', clanTaskIcon10);
        this.load.image('clan-task-icon-11', clanTaskIcon11);
        this.load.image('clan-task-icon-12', clanTaskIcon12);
        this.load.image('clan-task-icon-13', clanTaskIcon13);
        this.load.image('clan-task-icon-14', clanTaskIcon14);
        this.load.image('clan-task-icon-15', clanTaskIcon15);
        this.load.image('clan-task-icon-16', clanTaskIcon16);
        this.load.image('clan-task-icon-17', clanTaskIcon17);
        this.load.image('clan-task-icon-18', clanTaskIcon18);
        this.load.image('clan-task-icon-19', clanTaskIcon19);
        this.load.image('clan-bank-button', clanBankBtn);
        this.load.image('clan-tab-icon-sheep', clanTabIconSheep);
        this.load.image('clan-tab-icon-chicken', clanTabIconChicken);
        this.load.image('clan-tab-icon-cow', clanTabIconCow);
        this.load.image('clan-tournament-header', clanTournamentHeader);
        this.load.image('clan-tournament-decor', clanTournamentDecor);
        this.load.image('clan-tournament-animal-bg', clanTournamentAnimalBg);
        this.load.image('clan-tournament-plate-bg', clanTournamentPlateBg);
        this.load.image('clan-sheep-1', clanSheep1);
        this.load.image('clan-sheep-2', clanSheep2);
        this.load.image('clan-sheep-3', clanSheep3);
        this.load.image('clan-sheep-4', clanSheep4);
        this.load.image('clan-sheep-5', clanSheep5);
        this.load.image('clan-sheep-6', clanSheep6);
        this.load.image('clan-sheep-7', clanSheep7);
        this.load.image('clan-sheep-8', clanSheep8);
        this.load.image('clan-sheep-9', clanSheep9);
        this.load.image('clan-sheep-10', clanSheep10);
        this.load.image('clan-sheep-11', clanSheep11);
        this.load.image('clan-sheep-12', clanSheep12);
        this.load.image('clan-chicken-1', clanChicken1);
        this.load.image('clan-chicken-2', clanChicken2);
        this.load.image('clan-chicken-3', clanChicken3);
        this.load.image('clan-chicken-4', clanChicken4);
        this.load.image('clan-chicken-5', clanChicken5);
        this.load.image('clan-chicken-6', clanChicken6);
        this.load.image('clan-chicken-7', clanChicken7);
        this.load.image('clan-chicken-8', clanChicken8);
        this.load.image('clan-chicken-9', clanChicken9);
        this.load.image('clan-chicken-10', clanChicken10);
        this.load.image('clan-chicken-11', clanChicken11);
        this.load.image('clan-chicken-12', clanChicken12);
        this.load.image('clan-cow-1', clanCow1);
        this.load.image('clan-cow-2', clanCow2);
        this.load.image('clan-cow-3', clanCow3);
        this.load.image('clan-cow-4', clanCow4);
        this.load.image('clan-cow-5', clanCow5);
        this.load.image('clan-cow-6', clanCow6);
        this.load.image('clan-cow-7', clanCow7);
        this.load.image('clan-cow-8', clanCow8);
        this.load.image('clan-cow-9', clanCow9);
        this.load.image('clan-cow-10', clanCow10);
        this.load.image('clan-cow-11', clanCow11);
        this.load.image('clan-cow-12', clanCow12);
        this.load.image('shop-btn', shopBtn);
        this.load.image('shop-btn-disable', shopBtnDisable);
        this.load.image('decor-left', decor1);
        this.load.image('decor-right', decor2);
        this.load.image('clan-star', clanStar);
        break;
      case 22:
        this.load.image('modal-header-event-end', headerEventEnd);
        this.load.image('clan-window-leader-plate-2', clanWindowLeaderPlate);
        this.load.image('clan-window-line', clanWindowLine);
        this.load.image('done-chapter-button', doneChapterButton);
        this.load.image('clan-award-plate', clanRewardPlate);
        this.load.image('decor-left', decor1);
        this.load.image('decor-right', decor2);
        this.load.image('clan-big-medal', bigMedal);
        this.load.image('clan-big-star', bigStar);
        this.load.image('clan-glow', clanGlow);
        this.load.image('clan-building', clanBuilding);
        this.load.image('circle', circle);
        this.load.image('clan-diamond-coin', clanDiamondCoin);
        break;
      case 23:
        this.load.image('sale-window-header', saleWindowHeader);
        this.load.image('sale-window-flags', saleWindowFlags);
        this.load.image('sale-window-double-count', saleWindowDoubleCount);
        this.load.image('sale-window-half-price', saleWindowHalfPrice);
        this.load.image('sale-window-header', settingsWindowHeader);
        this.load.image('close-window-btn', closeWindowBtn);
        this.load.image('sale-icon-chicken-collector-improve', saleIconChickenCollectorImprove);
        this.load.image('sale-icon-chicken-collector-price', saleIconChickenCollectorPrice);
        this.load.image('sale-icon-chicken-feed', saleIconChickenFeed);
        this.load.image('sale-icon-chicken-herd', saleIconChickenHerd);
        this.load.image('sale-icon-chicken-money', saleIconChickenMoney);
        this.load.image('sale-icon-chicken-price', saleIconChickenPrice);
        this.load.image('sale-icon-chicken-repository-improve', saleIconChickenRepositoryImprove);
        this.load.image('sale-icon-clan', saleIconClan);
        this.load.image('sale-icon-cow-collector-improve', saleIconCowCollectorImprove);
        this.load.image('sale-icon-cow-collector-price', saleIconCowCollectorPrice);
        this.load.image('sale-icon-cow-factory-improve', saleIconCowFactoryImprove);
        this.load.image('sale-icon-cow-feed', saleIconCowFeed);
        this.load.image('sale-icon-cow-herd', saleIconCowHerd);
        this.load.image('sale-icon-cow-money', saleIconCowMoney);
        this.load.image('sale-icon-cow-price', saleIconCowPrice);
        this.load.image('sale-icon-cow-repository-improve', saleIconCowRepositoryImprove);
        this.load.image('sale-icon-diamond-count', saleIconDiamondCount);
        this.load.image('sale-icon-package-price', saleIconPackagePrice);
        this.load.image('sale-icon-sheep-collector-improve', saleIconSheepCollectorImprove);
        this.load.image('sale-icon-sheep-collector-price', saleIconSheepCollectorPrice);
        this.load.image('sale-icon-sheep-feed', saleIconSheepFeed);
        this.load.image('sale-icon-sheep-herd', saleIconSheepHerd);
        this.load.image('sale-icon-sheep-money', saleIconSheepMoney);
        this.load.image('sale-icon-sheep-price', saleIconSheepPrice);
        this.load.image('sale-icon-sheep-repository-improve', saleIconSheepRepositoryImprove);
        this.load.image('modal-bg-plate', modalBgPlate);
        break;
      case 24:
        this.load.image('review-bg', reviewBg);
        this.load.image('review-btn-like', reviewBtnLike);
        this.load.image('review-btn-dislike', reviewBtnDislike);
        break;
      case 25:
        this.load.image('profile-window-header', profileWindowHeader);
        this.load.image('profile-window-bg', profileWindowBg);
        this.load.image('profile-window-level', profileWindowBg);
        this.load.image('avatar-0', avatar0);
        this.load.image('avatar-1', avatar1);
        this.load.image('avatar-2', avatar2);
        this.load.image('avatar-3', avatar3);
        this.load.image('avatar-4', avatar4);
        this.load.image('avatar-5', avatar5);
        this.load.image('avatar-6', avatar6);
        this.load.image('avatar-7', avatar7);
        this.load.image('avatar-8', avatar8);
        this.load.image('buy-avatar-plate', buyPlate);
        this.load.image('avatar-frame', avatarFrame);
        break;
      case 26:
        for (let i = 1; i <= 275; i += 1) {
          this.load.image(`ach${i}-status`, achievementIcon1);
        }
        break;
      default:
        break;
    }
    
}