export default [
  {
    id: 1,
    type: 1,
    state: 0,
    count: Phaser.Math.Between(5, 20),
    done: false,
    got_awarded: false,
    progress: 0,
    diamonds: 1,
  },
  {
    id: 2,
    type: 2,
    state: 0,
    count: Phaser.Math.Between(5, 20),
    done: false,
    got_awarded: false,
    progress: 0,
    diamonds: 1,
  },
  {
    id: 3,
    type: 3,
    state: 0,
    count: Phaser.Math.Between(2, 3),
    done: false,
    got_awarded: false,
    progress: 0,
    diamonds: 1,
  },
  {
    id: 4,
    type: 4,
    state: 0,
    count: Phaser.Math.Between(5, 20),
    done: false,
    got_awarded: false,
    progress: 0,
    diamonds: 1,
  },
  {
    id: 5,
    type: 5,
    state: 0,
    count: Phaser.Math.Between(5, 20),
    done: false,
    got_awarded: false,
    progress: 0,
    diamonds: 1,
  },
  {
    id: 6,
    type: 6,
    state: 0,
    count: Phaser.Math.Between(5, 20),
    done: false,
    got_awarded: false,
    progress: 0,
    diamonds: 1,
  },
  {
    id: 7,
    type: 7,
    state: 0,
    count: Phaser.Math.Between(5, 20) * 10,
    done: false,
    got_awarded: false,
    progress: 0,
    diamonds: 1,
  },
  {
    id: 8,
    type: 8,
    state: 0,
    count: Phaser.Math.Between(2, 4),
    done: false,
    got_awarded: false,
    progress: 0,
    diamonds: 1,
  },
  {
    id: 9,
    type: 9,
    state: 0,
    count: Phaser.Math.Between(2, 4),
    done: false,
    got_awarded: false,
    progress: 0,
    diamonds: 1,
  },
  {
    id: 10,
    type: 10,
    state: 0,
    count: Phaser.Math.Between(5, 20),
    done: false,
    got_awarded: false,
    progress: 0,
    diamonds: 1,
  },
  {
    id: 11,
    type: 11,
    state: 0,
    count: Phaser.Math.Between(5, 20),
    done: false,
    got_awarded: false,
    progress: 0,
    diamonds: 1,
  },
  {
    id: 12,
    type: 12,
    state: 0,
    count: Phaser.Math.Between(5, 20),
    done: false,
    got_awarded: false,
    progress: 0,
    diamonds: 1,
  },
  {
    id: 13,
    type: 13,
    state: Phaser.Math.Between(5, 10),
    count: Phaser.Math.Between(2, 4),
    done: false,
    got_awarded: false,
    progress: 0,
    diamonds: 1,
  },
  {
    id: 14,
    type: 14,
    state: 0,
    count: Phaser.Math.Between(2, 4),
    done: false,
    got_awarded: false,
    progress: 0,
    diamonds: 1,
  },
  {
    id: 15,
    type: 15,
    state: 0,
    count: Phaser.Math.Between(5, 20),
    done: false,
    got_awarded: false,
    progress: 0,
    diamonds: 1,
  },
  {
    id: 16,
    type: 16,
    state: 0,
    count: Phaser.Math.Between(5, 10),
    done: false,
    got_awarded: false,
    progress: 0,
    diamonds: 1,
  },
  {
    id: 17,
    type: 17,
    state: 0,
    count: Phaser.Math.Between(2, 4),
    done: false,
    got_awarded: false,
    progress: 0,
    diamonds: 1,
  },
  {
    id: 18,
    type: 18,
    state: 0,
    count: Phaser.Math.Between(2, 10) * 10 * 60,
    done: false,
    got_awarded: false,
    progress: 0,
    diamonds: 1,
  },
  {
    id: 19,
    type: 19,
    state: 0,
    count: 1,
    done: false,
    got_awarded: false,
    progress: 0,
    diamonds: 1,
  },
];
